---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack-dependencies
  labels:
    override-target-namespace: 'true'
spec:
  path: "./flux/apps/observability/kube-prometheus-stack/dependencies"
  dependsOn:
  - name: external-secrets-bitwarden
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack-app
  labels:
    override-target-namespace: 'true'
spec:
  path: "./flux/apps/observability/kube-prometheus-stack/app"
  dependsOn:
  - name: kube-prometheus-stack-dependencies
  - name: tailscale-app
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack-oauth-egress
  labels:
    override-target-namespace: 'false'
spec:
  path: "./flux/apps/observability/kube-prometheus-stack/oauth-egress"
  dependsOn:
  - name: kube-prometheus-stack-app
  - name: tailscale-app
