---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubelet-device-plugins-app
spec:
  path: "./flux/apps/infra/kubelet-device-plugins/app"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pocket-id-dependencies
spec:
  path: "./flux/apps/infra/pocket-id/dependencies"
  dependsOn:
  - name: external-secrets-bitwarden
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pocket-id-app
spec:
  path: "./flux/apps/infra/pocket-id/app"
  dependsOn:
  - name: pocket-id-dependencies
  - name: cert-manager-app
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: omada-controller-app
spec:
  path: "./flux/apps/infra/omada-controller/app"
