---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubelet-device-plugins-app
  labels:
    override-target-namespace: 'true'
spec:
  path: "./flux/apps/infra/kubelet-device-plugins/app"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pocket-id-dependencies
  labels:
    override-target-namespace: 'true'
spec:
  path: "./flux/apps/infra/pocket-id/dependencies"
  dependsOn:
  - name: external-secrets-bitwarden
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pocket-id-app
  labels:
    override-target-namespace: 'true'
spec:
  path: "./flux/apps/infra/pocket-id/app"
  dependsOn:
  - name: pocket-id-dependencies
  - name: cert-manager-app
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: omada-controller-app
  labels:
    override-target-namespace: 'true'
spec:
  path: "./flux/apps/infra/omada-controller/app"
