---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack-app
  labels:
    override-target-namespace: 'true'
spec:
  path: "./flux/apps/infra/kube-prometheus-stack/app"
  dependsOn:
  - name: tailscale-app
