
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-storage-version-migrator-app
spec:
  path: "./flux/apps/platform/kube-storage-version-migrator/app"
  dependsOn:
  - name: anza-labs-github-io-charts
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-app
spec:
  path: "./flux/apps/platform/cert-manager/app"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuers-cloudflare
spec:
  path: "./flux/apps/platform/cert-manager/issuers/cloudflare"
  dependsOn:
  - name: cert-manager-app
  - name: external-secrets-bitwarden
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubearmor-operator-app
spec:
  path: "./flux/apps/platform/kubearmor-operator/app"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubewarden-crds
spec:
  path: "./flux/apps/platform/kubewarden/crds"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubewarden-app
spec:
  path: "./flux/apps/platform/kubewarden/app"
  dependsOn:
  - name: kubewarden-crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-app
spec:
  path: "./flux/apps/platform/external-secrets/app"
  dependsOn:
  - name: charts-external-secrets-io
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-bitwarden
spec:
  path: "./flux/apps/platform/external-secrets/bitwarden"
  dependsOn:
  - name: external-secrets-app
  - name: cert-manager-app
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-dependencies
spec:
  path: "./flux/apps/platform/tailscale/dependencies"
  dependsOn:
  - name: external-secrets-bitwarden
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-app
spec:
  path: "./flux/apps/platform/tailscale/app"
  dependsOn:
  - name: tailscale-dependencies
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: reloader-app
spec:
  path: "./flux/apps/platform/reloader/app"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-upgrade-controller-app
spec:
  path: "./flux/apps/platform/system-upgrade-controller/app"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hwameistor-dependencies
spec:
  path: "./flux/apps/platform/hwameistor/dependencies"
  dependsOn:
  - name: system-upgrade-controller-app
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hwameistor-app
spec:
  path: "./flux/apps/platform/hwameistor/app"
  dependsOn:
  - name: hwameistor-dependencies
