---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kured
  labels:
    source: helm
spec:
  chart:
    spec:
      chart: kured
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kubereboot-github-io-charts
        namespace: placeholder
      version: "5.6.1"
  interval: 30m0s
  timeout: 10m0s
  releaseName: kured
  targetNamespace: kured-system
  test:
    enable: true
    ignoreFailures: true
  driftDetection:
    mode: enabled
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
      strategy: uninstall
      remediateLastFailure: true
  valuesFrom:
  - kind: Secret
    name: kured-shoutrrr
    valuesKey: url
    targetPath: configuration.notifyUrl
