---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id-app
  labels:
    source: helm
spec:
  chart:
    spec:
      chart: pocket-id
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: anza-labs-github-io-charts
        namespace: placeholder
      version: "1.4.3"
  interval: 30m0s
  timeout: 10m0s
  releaseName: pocket-id
  targetNamespace: pocket-id-system
  test:
    enable: true
    ignoreFailures: true
  driftDetection:
    mode: enabled
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
      strategy: uninstall
      remediateLastFailure: true
  values:
    host: pocket-id.tail4d421.ts.net
    ingress:
      enabled: true
      className: tailscale
      host: pocket-id
      annotations:
        tailscale.com/funnel: "true"
      tls:
        - hosts:
            - pocket-id
    persistence:
      data:
        enabled: true
    backup:
      enabled: true
      secret:
        replicas:
          - path: /pocket-id
            region: auto
            bucket: backups
            endpoint: 556bb9fcc3f4395cafc528bad941b0b3.r2.cloudflarestorage.com
            forcePathStyle: true
  valuesFrom:
    - kind: Secret
      name: pocket-id-backup
      valuesKey: access-key
      targetPath: backup.secret.accessKey
    - kind: Secret
      name: pocket-id-backup
      valuesKey: secret-key
      targetPath: backup.secret.secretKey
