all:
    children:
        #ENC[AES256_GCM,data:G0KwrBeSb0u8kinBaLqh6ms4M85CEdURGsg9XUDzEKS6m63uY/siAvwYz5VvrGCbcC1lQRwnBMwljozk,iv:HmVOWsAe5K4pkkKH4INyDz1g6PhGJTpLiUFYg+eYtLI=,tag:dMrYUY552wP0V1zahRCMjw==,type:comment]
        #
        #ENC[AES256_GCM,data:3Ceu8xl6+gf14gFPYA==,iv:hzoeJ/2lPNABHUIUuhwCuXzTCnjhJu2N2zN3hiHhKec=,tag:JAFnYYJwT7qLfPSQPuW3uw==,type:comment]
        #
        #ENC[AES256_GCM,data:98Lat7NNrTVBs3Vy4nfOqIIhGPOFNnfjsG7e0NEUN+wUT0xFtUD20dyu6TUP6u3jmnWzMFCP+w71ciPQ,iv:2iW0NWbEPYc34hp/cU++tPoDJsUunknh8NzMe8qrFLw=,tag:4nU9ypm9khbpsgUJGI1dcA==,type:comment]
        builders:
            hosts:
                builder1:
                    ansible_host: ENC[AES256_GCM,data:Q9hJrZ7JFSNcj4KThA==,iv:xXgypNnw+JPDcSnKO8GqG/gykFPAG0s6nc/XlfOXESI=,tag:E9kvx9D5AGUAItP897WH4Q==,type:str]
                    ansible_user: ENC[AES256_GCM,data:6kEGZSfQZDY=,iv:KhoMUVP6F7qbODA496QW261TSoDWlz79n+vC54sGEU8=,tag:1YwkjKLFyToHYzSP/Ocxqw==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:pKwlLVHHP0Mxajh1rVwc540=,iv:ptejgoVCiDfoIN/kDNRXZ5HwYUm9ntquW/rXgKMx3DE=,tag:4abWIzwYxA6PRJOgo7t2rA==,type:str]
        installer-stage1:
            hosts:
                pi5-installer-s1:
                    ansible_host: ENC[AES256_GCM,data:7WPV6zIRwA+dqmu4YQ==,iv:tbtwMYsyH0f1iuHgSBINmJl1/aRAXbAjuCIFEMpXB6o=,tag:FgzOHa0AojGZeiCwYL4SLg==,type:str]
                    ansible_user: ENC[AES256_GCM,data:Q+cZfsKjLeY=,iv:/gFrC0POhpO/yODBifV/NkDb0IKX9jFoQDHEZc8FzVA=,tag:r6ZVkKHlz+j/9Xj1BlnXVw==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:43WU62+JzN7Oij0PsrV3obA=,iv:zPsasjmg/ki9OJNGaVTdMyMy7tQTw6nFS2pqZjY2hRU=,tag:59XCGhSr5PB4lkqPn16dmw==,type:str]
        installer-stage2:
            hosts:
                pi5-installer-s2:
                    ansible_host: ENC[AES256_GCM,data:BNOfnThDFy2Zs1ku,iv:PkPOHF++lJBzaiu5ZfE230MukRpZxxqmwk12QZR0z6c=,tag:l6J+tI+3ScGz6SIDRgSL2w==,type:str]
                    ansible_user: ENC[AES256_GCM,data:F8OTZ953ajk=,iv:BFQhViEFs3L/UxhOla97nvNBkrguZa+thViucpXl0og=,tag:03v5+xIZuH/2MUrsjX/2sg==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:B7b8b9hhTpmKs4yGBJjoqMI=,iv:vpf8OKV75i4p1uD5Qd7SnzgbPG1ZXBjz5MgZceUWYYE=,tag:2FD4uaQdYG53xe5WjV0VvQ==,type:str]
                    tailscale_authkey: ENC[AES256_GCM,data:RV8vA4KZc3tRV2VuUueE0MC0DSokPM5p5uHTH6hGOLceHQbfgRrcWSAysC5vxL4Q94SkYT+K9Tyvt9IPS8Y=,iv:rM25uvGFE3A2wLfcE4oWSrV7xn5+gvrN7yRQyKJPpgU=,tag:bnSpuDl23GJtoldJxHT8Kw==,type:str]
        #ENC[AES256_GCM,data:r5RPe1FziUGzwvYSTiHaeO25+P9MIAxWpRUU57EcSncOEdWdny7adIZVqMHsirJn1Y7Qp1VHGYXFwFpf,iv:kb3W2/sqEUEbvD+fULfCkxUpoZyXWgQBvXE7FPjDdnU=,tag:e7DtPX4ZcfFJZrNgmP8KXw==,type:comment]
        #
        #ENC[AES256_GCM,data:ob//KV2NVdsnGwKn3xGD1yU=,iv:GkkyAXy7YK2VUxjTSteZR9prb3xtT7DtqserM3J9Rks=,tag:8sm5FTsdavJYLZimglWR8g==,type:comment]
        #
        #ENC[AES256_GCM,data:od7R8CMeHxmotLfYD0D/fgjqyX0sf0LwjZZ6pDa9ClYZybc40eXMowSvWyh7DI3PA1I9wFKAb/1sLFEZ,iv:NIpmABUKGUGbKA5+0kwpuM05q6PStPWFZv2PRn2arsk=,tag:l3awv5MFRzJ24nHfOuOI+g==,type:comment]
        routers:
            hosts:
                cm5:
                    #ENC[AES256_GCM,data:LpYHoLoNe8mTKGHqZ++sVqjKEqPo5w+SoyrdJmqafQ==,iv:T+4sT3j9NCmwU6Pt7E5PfqbWa8+fhCtaiopz2+8o2mA=,tag:/BJItODtreY/QSDQ67FNPA==,type:comment]
                    ansible_host: ENC[AES256_GCM,data:AU7OXTuhur+tfIU=,iv:R+Qatkw06NsQ+BEMMmnwOZPjOhQiP8SbayEHIP1TV2E=,tag:ckIapSOtSk9LjAIXtcGvFg==,type:str]
                    ansible_user: ENC[AES256_GCM,data:WwGAIg==,iv:4525mhzsuE0TwnzURTz0mzki0UOWnAWb/DWaXGmqzDU=,tag:nNZVkr1PGq0OSXqINhZXKw==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:BdIVCei0thP8zUCJFRDw6jw=,iv:XJ8XamCJkpp7H+9r9AkXoK3IPyr4PGIXr2jCNECogOg=,tag:cEPwoUgn2SeUg5Qa+tcgVw==,type:str]
        pi:
            hosts:
                pi5:
                    ansible_host: ENC[AES256_GCM,data:uieaDwcN+WGT7X9+,iv:0DdV7/Ig4HwMbIU/+2gLAmMjtRfGmyyBJMD/2nhcE0k=,tag:7NAOP5/EXmENF16oNJ3prA==,type:str]
                    ansible_user: ENC[AES256_GCM,data:Pp/kgIqjI+A=,iv:RtlieD8jqDifzFjODUJAVT143xFgvAORjBqLdCluxwA=,tag:tBcQ+iJU68XNEI21H7tEDQ==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:z1pzf+V38ZeRCHVz9JvSYMQ=,iv:3M0VvEzq2tR6EJt1VyXSlaUSzsQ23Z8xRr+FSa8voUA=,tag:2GV4/2kscWIHdhBzQ3Glbg==,type:str]
        solo:
            hosts:
                mars:
                    ansible_host: ENC[AES256_GCM,data:zRXwZ7n+fgsIkVwt,iv:te5HNZZurpXS4bL9TjKM029Kl79sa+Gz83479289BSk=,tag:Ch5bWkQQ+xX5T5At/85h+A==,type:str]
                    ansible_user: ENC[AES256_GCM,data:GtWyJzmxbck=,iv:7Or2K9uc0B3OFvVUAPe8cWwQhX+MsHMRD35oUBMux2Q=,tag:JIgdHY+o8QLww3hhqdNJLA==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:c/4SUqCAua7yHylXi4ZllMc=,iv:5rKTLwT46XhekQ171CLGD9GQqk0sLjnyBMNB/9F2RVM=,tag:1526qFip+l6RpQqlRJeYjQ==,type:str]
        #ENC[AES256_GCM,data:HvyIWp+7WF0g1s11wcu/B3vG/NTQusWPbcSQrHcod8QFsDxcw4/v5LglE1PzBcCc9vZ7cRC8p2mzMOIp,iv:nvIwOyJ++tkgYNgJUUOlLbYDVdhSVLBYsY3LiqT2mNw=,tag:DSSJCViV0E5L+WkQyie0uA==,type:comment]
        #
        #ENC[AES256_GCM,data:3JV/jyg6,iv:ol41jh/n22pMKza8Bc2Y7KJI8aqbbt2hmBimTAPGdfc=,tag:d/h+dNXSKj0bDD+Ze8JwuA==,type:comment]
        #
        #ENC[AES256_GCM,data:K2z01D2dHxvIUda8eHgfNQSh3nIgMzmiYlY/amI/aJjugwdlol9+a+6AGQQANVUTCoCr998SKx9IqBQz,iv:hExndkGw9vbDxvmmrwHtjfL3Wr1BWgUIJj9fqLyMqKE=,tag:nt2nyQnGfKlVQUqHsXYqsg==,type:comment]
        alpine:
            hosts:
                frog:
                    ansible_host: ENC[AES256_GCM,data:si4TJhCGHeSfOvnP6GU=,iv:jgpFiloBkt50cezlmNE+G9KyMk8vPL+hlZ3nLpA50ec=,tag:Og5M6OlauQosS+JZi92dmw==,type:str]
                    ansible_user: ENC[AES256_GCM,data:aIVoHg==,iv:GIXiTG/VbvGJItUQXuB5wdYdVHHGvrbOuVmAMy+RYNo=,tag:prJKL41KpeeSedcGUzv7AA==,type:str]
                    ansible_port: ENC[AES256_GCM,data:h9qJK1o=,iv:pcCdGj+tQuq/5VGN511abyW2Na6bNKgfiTqPWzEOR7Y=,tag:HOQVmL708Nry9ACB+Htn5Q==,type:int]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:aqmcb8CLj+15/wQamauIhPM=,iv:ZneG7Mv4UrLQWc1Dec65oLAYSh36UyZw2A1ruYsjSiU=,tag:lKsusbIS888OmX8pNtTldw==,type:str]
                    cloudflared_token: ENC[AES256_GCM,data:+G+G0vbD7U+SA1DHyeittd4MROd5bzTSuIA2ei3hZQTw8qLFkeAC/jIxTdRA29wJBIK4gOz6UcTMsEdmpolsvgh0bjbhQmP8ksVqpUvMWpwW7MqXKsKorfRJ1dDxe7QXqKd8oVsfZhKfLtoTIUa+xVt4DR8pVSFs0FduzJkC952Kx6BvTUJ7Vrv4lR652BUXgjfzQROfiVlrVZcl8n9Ff5Ta2jrKvDf2A2wxfEAYJ8wQFkMvDIpZXA==,iv:Wzoa4wUjd2p4RSEaW1bCLysLnf6zSbYBwn35l9v/ex0=,tag:ynZDDiAcfwTUjxlD6bNWJA==,type:str]
sops:
    lastmodified: "2026-03-02T21:45:08Z"
    mac: ENC[AES256_GCM,data:0guABDZKXJKAsHA19ifPHax1gtNgi0+WrDJmvJVE1U3CliGdTPqo07PAznp0vKpODjNMPWFmburN8TJrKXQ7o1sTK+GNV7O4EAusH1CTjC/eHEF81x30wvGkt4V7U7tYUx++nVjd1mcHSUMMO75JzKW/RXKsDic2BgFriPGYPAo=,iv:aYhW8FgUAGYoChZxDPAKcueLt5fbRK+tNUNik5zlc50=,tag:Ri+fSeXpDlSdLQNCiuK34w==,type:str]
    pgp:
        - created_at: "2026-03-02T21:45:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2aYMUUzTqIRAQ//YW0MKDdk9B4vU01jNz/vCK/VSrElRgFYOc0S9JO4aTg6
            D5C3fwg/OnfoJewjFvl50jQ2a4d5J6G9zxG8vI+6XKbflmhIli2Xq3eNL+H5VsTe
            yS0s7bI279EgfEnOUSduiozJH4TGLMJU03LAoRWQGi2b5kDxnHeW2j5BAsW9X7MD
            +1X5W+7dJcYYP6xwoCXbgAK7r9itlvWHs3C2WFVUJknU6vLlu2jDMGrPEi33RJez
            fMxIfbwhjuKNAeG5anFAKH+IsAW2r6LzVJE14dgv5ISPRdSA0s57VLSnsHp30Gt4
            1CBrsjMxUudxmBOwWO04DjK4svpGAZnWBQgRDGhcNZ/K7HrMFtymzQEfSDbayqPE
            6FRsW0A25tRVyjt0LP17MtJizHRRLmNFHOc1AthzrPD8JkIqxPnM6RXTZ1p3uHeS
            YL16TSb83f7FYNO9lulJ+BLAlDL0dHfYFiP1q7nXiV2ETI9xBJXE9dXFzgJmIc5E
            R0U3kfhciY9IcnJw21H+uGwm5dZByQD81XZWcyN4Rd+kymKgXl6dXTt5KQxaMNTd
            sMNmwF13jcOmBeBqjtHHiInw0kuK/oPl3Toq8qP4bfauV0uzfQuDSnH9z3qg2pSz
            q/z5Kbkbtq4YPLizyut+HoNn5Hx54+CzhLtWR4K/dqx1PZCuLcDteEOG2oz/GvjU
            aAEJAhA/nYMca4V/lX9Lt7y1RQOC1G+QeVC9tkRreDxgCzP5VZsBoGUMAC36ajXV
            orvGBDZYv+5iwg8zkH9DGZd4TOHfQnY1A8emtkcrv/byQCYHMBixCaeOCJamnKxJ
            cZzDKBEhuDUQ
            =fD0L
            -----END PGP MESSAGE-----
          fp: 4C8C1857C468123F57E5C7E7A05D361B64156AA7
    unencrypted_suffix: _unencrypted
    version: 3.11.0
