- op: add
  path: /spec/patches
  value:
    - patch: |
        - op: replace
          path: /spec/sourceRef/namespace
          value: flux-apps
      target:
        group: helm.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
    - patch: |
        - op: replace
          path: /spec/chart/spec/sourceRef/namespace
          value: flux-apps
      target:
        group: helm.toolkit.fluxcd.io
        version: v2
        kind: HelmRelease
        labelSelector: source=helm
    - patch: |
        - op: replace
          path: /spec/chartRef/namespace
          value: flux-apps
      target:
        group: helm.toolkit.fluxcd.io
        version: v2
        kind: HelmRelease
        labelSelector: source=oci
