- op: add
  path: /spec/patches/0
  value:
    patch: |
      - op: add
        path: /spec/values/persistence/data/storageClass
        value: local-path
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
