apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: manifests
spec:
  interval: 30m
  path: ./flux/manifests/k3sup
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
