---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: perses-app
  labels:
    source: helm
spec:
  chart:
    spec:
      chart: perses
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: perses-github-io-helm-charts
        namespace: placeholder
      version: "0.14.7"
  interval: 30m0s
  timeout: 10m0s
  releaseName: perses
  targetNamespace: perses
  test:
    enable: true
    ignoreFailures: true
  driftDetection:
    mode: enabled
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
      strategy: uninstall
      remediateLastFailure: true
  values:
    config:
      security:
        enable_auth: true
        secure: true
        authentication:
          providers:
            oauth:
              - slug_id: pocket-id
                name: Pocket ID
                scopes:
                  - openid
                  - profile
                  - email
                auth_url: https://pocket-id.tail4d421.ts.net/authorize
                token_url: https://pocket-id.tail4d421.ts.net/api/oidc/token
                redirect_uri: https://perses.tail4d421.ts.net/api/auth/providers/oauth-github/callback
  valuesFrom:
  - kind: Secret
    name: perses-oauth-credentials
    valuesKey: client_id
    targetPath: config.security.authentication.providers.oauth[0].client_id
  - kind: Secret
    name: perses-oauth-credentials
    valuesKey: client_secret
    targetPath: config.security.authentication.providers.oauth[0].client_secret
