---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-backup
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: access-key
    remoteRef:
      key: "3f74e7ae-c333-4dd7-997b-b30701549436"
  - secretKey: secret-key
    remoteRef:
      key: "af3e102e-ca79-4e37-a2a5-b3070154636e"
