---
apiVersion: v1
kind: Namespace
metadata:
  name: victoria-metrics
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vm
  namespace: victoria-metrics
spec:
  interval: 5m0s
  url: https://victoriametrics.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
  namespace: victoria-metrics
spec:
  chart:
    spec:
      chart: victoria-metrics-single
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: vm
        namespace: victoria-metrics
      version: "0.28.0"
  interval: 30m0s
  timeout: 10m0s
  releaseName: victoria-metrics
  test:
    enable: true
    ignoreFailures: false
  driftDetection:
    mode: enabled
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
      strategy: rollback
      remediateLastFailure: true
  values: {}
