---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
  namespace: external-secrets
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://vault.bitwarden.com
      identityURL: https://identity.bitwarden.com
      auth:
        secretRef:
          credentials:
            name: bitwarden
            namespace: kube-system
            key: token
      bitwardenServerSDKURL: https://bitwarden-sdk-server.default.svc.cluster.local:9998
      caBundle: ''
      organizationID: 554098a1-1b76-4d11-89d1-b1c500b11b2e
      projectID: 2728ee07-5f6d-4c5c-97d8-b1c500b28bb9
