apiVersion: ENC[AES256_GCM,data:2do=,iv:kHZSZqHC9KBNvF1H6lgNb0/zDp+03C7+mzzvxCZGdgo=,tag:mhbyfPV6yJqcMkgD9PQqKw==,type:str]
kind: ENC[AES256_GCM,data:zrxDuY5e,iv:dHJNWfBHVbzBNQ7WfCbiwr9DB2YA9qrs4Mm/9c934FA=,tag:bN+cHCrgLkl6gRJZu55Biw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9ILV9B5kw613fTGQQIepkQ==,iv:yHj/qVoaNElFFpJwsZZXSdxD0xVlSUW++1nPCLz89Yg=,tag:qB1a0cL997hrEHitqpVh+w==,type:str]
    namespace: ENC[AES256_GCM,data:oIoUhujBX3dE,iv:tudx07q/9UKNLTdWZoW7RfCMg50qNVYE/1iSRyBy+Ro=,tag:ZA2ohGNFmg0mXQSpApE7Ag==,type:str]
stringData:
    access-key: ENC[AES256_GCM,data:5eiYbxN2dEOkybODHNIRJtM0RT1bVeh6z9TpaBgZjhE=,iv:FnRonrvmbgImlQxBXOfF2MB3dPqES51M6SUh8YHS9kg=,tag:E2++yQJRH2v0GQhH9wPWhQ==,type:str]
    secret-key: ENC[AES256_GCM,data:yCiCGt8ibg+srQ+zDc+aQLyTSPP1rcpfL0YwSC47uxvM3Oueu0g07Zg5uXJjVj/NFVNysJrmZM7/dJN5QiQaFg==,iv:+xgsEgKgFdh0RL3aTm32aKd/cuqkGYwILRzB/vxHB44=,tag:m431wwvW9d7FI1fty2ED3w==,type:str]
sops:
    lastmodified: "2025-11-03T16:11:18Z"
    mac: ENC[AES256_GCM,data:KTnmfVb2tnczg++VaE2FLNEC9Lb7vKDRJ1aVCNoDM0Hi+84BeQw3h0ahTc3eY1X4IobWP+mteHBUVAbqysS8/52cuL0ESAdHY3hWE5Py1sU6VrYQVrqWBQq9w/Ie9mG7dOAUiUk4F0J9iCQzYVFhup8t3gcP5W+EGhuL8W5JyiQ=,iv:v46bNPUkRQF9JwiBUbmExds/ckQMtZTpJXTpwyGi8fg=,tag:Broj9BCeC1OhWCqfDmrenQ==,type:str]
    pgp:
        - created_at: "2025-11-03T16:11:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2aYMUUzTqIRARAA18eIgWnfuIw8FFSZCQObvTkXrqb7iIGdjxPB8XAWu7Xf
            uxE9CoRbS2HUaXEBS6JaQOdwZseSnen9/ixyXTI8Qe0U+dtI6oANytZg1xAa8WLq
            ler1yY7hIZh/OCRelktK8D5IahIBjzp3561fpqmlLSt/Rs1f1P3r8eF/TyOutf4F
            +aWoq5IOKWV50eUdoEvYSL2Du8Mwz341Pc7lubvfOUnJTGhLTTeZxA2NCnwwpWDa
            h2g9/MrH2TiwbVPhJ2w9g+8DFKhigy8rQXkmIcZyqhho1BKPw4TVdPky3HmXfpHy
            wxo9ioIO11MIDZkS71DSjxEtSPo41oomzfA+tHQ2jbQ4IYg/VZ2wsKNj++XT1DFB
            oJFAKmwSTpCUIWgnkpeTu1k/3olZD9uRvJCyl5qqc1bMMEiTEGL0IWwKZ9VjM5i+
            aJAq7vvTzgAWqENtjKFAuvS9VR8OuzCw9s/c/4ziJd90ZdIWAgdVCL7Bnql5KgYb
            i99fBJQM59Bv/WL4GtoKzddQ4QyNNZHcDfFOK0iDmZQdydbVgBCJH67PhTWeaU9b
            s8LzcHlBNKS/cvKsSw+SH4c59Tw3FbbGeyx01Xu1YHZI2e1bamsO+38JJBgLdJtL
            gawyItxcw9D2gRsJlUPQ1zEGcC5FQ8EOKX+VhJ3TdMZcjyzKk8v+m23hu0I0VL/U
            ZgEJAhBGEDpUQRV4wxQ+NcD3NXwQuHNoODEsopVJ5d1ad8ckd7EFmkBrYHOVaD6F
            Wl+739A9phaNYadLujUKtRUQkHBzJwnkOPCvzjP5FrPXnL7Mu9HmdUrkmatoPUSc
            E8qjPGBrBQ==
            =0a/W
            -----END PGP MESSAGE-----
          fp: 4C8C1857C468123F57E5C7E7A05D361B64156AA7
    unencrypted_suffix: _unencrypted
    version: 3.11.0
