apiVersion: ENC[AES256_GCM,data:Ga8=,iv:n3HT+sUMqi6rapPNPS8jYNfB+959yQY7v7n+YEDdL74=,tag:NJ4DuHM3k1qOhNgXniBXhg==,type:str]
kind: ENC[AES256_GCM,data:cSrZqEwH,iv:cF54h9WItcMKF2XHO/WRPFKxjCyX2K+u6DeFDlrINpw=,tag:mRbsnK67yh0wPdacUyYN2A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:z4ih5djMjfF59btguindOQ==,iv:+p6uOvBtm2Z0B7hKIUYmErgqwq/OILTcGgGFrpY0t2s=,tag:gS5iLbYsqALrMxCwUDppxw==,type:str]
    namespace: ENC[AES256_GCM,data:dC/HLOKlyjAm,iv:qNnyd7kjh2SRMMc3i2jbuTJupE/CvaTa3Oqe5tDmoQw=,tag:DZOUcZFIRHwpwQTxR96W0w==,type:str]
stringData:
    access-key: ENC[AES256_GCM,data:B4tbLmpKACSNd9h1kfwYMlqogv13KIm4Knayf19zEuM=,iv:dYX5Puoo/fw4UgUSjT2ZSJ04Y97Z/imdqWkGzBr+GXU=,tag:dLhnfVzJuDI+Rj/yHtUi3g==,type:str]
    secret-key: ENC[AES256_GCM,data:qjik3I98aAXHKiQMWpYvJ4cltg/u4KJeCV4g6A55xLIHmco/PIPqZkvA/6QHmh9+qJXnZh4Y4/p0yoDgczMZ6A==,iv:ybEO/VwWh8L3Yuzy0A+IwjKiytfjXl3AyyYx+u5SBbY=,tag:Fh/UXPLOxv8gRdsAsJPlwg==,type:str]
sops:
    lastmodified: "2026-01-06T18:09:18Z"
    mac: ENC[AES256_GCM,data:9pIhQ53cw76ErYgqVnEapj0jddWm5yr3UAJa+THMl58T+hAI7SeFSPXipj9kX3pB0tisNtBa7GH16lVzYJS7NlRS7MjN4QsYaTweLbIsl57fmUGSvUr57GzRBplwz9ALNuUgK7BkoXGtlQf2AZXuREYdz7LanzcTfCEMtyMUYv8=,iv:LjU69lF/FK3+86NiUWjU1SxGDgKHa1uph/XQ7QRFw48=,tag:Nr+zESNfp1blExWEVs8/0Q==,type:str]
    pgp:
        - created_at: "2026-01-06T18:09:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2aYMUUzTqIRARAAzKXo22IphWWf9eL/qSdMhXdjVNWc7KZgvw83GGW8kG4b
            VSOYp06+6AA4tFSeRw/O2NRXHQxRwK8jp+LOH/tiOfev60Q/nbO0KEilujK8cIm0
            3uXnFnUkJc1OR3LQXxCK+dl6k1u1Qg4YwKoabDO1VAXbWrOtu6Ao/yYbLH5AN0L9
            93GlQfIAmJIjJ4TmhvM8347H1pnSXFHIEqM6fbZjr26swFhUtnlx9F6ANY0ZmnY1
            h9PY9KWDMYh6rwkEieZUYrX/PrThMvrsEJJ4Dkc4jASAoeOZ2Ml1InTM6yRL0A2C
            rXRFt/1xwL6irTsF7pTrWAoKaKjXyXONKTx0q8jK3QEBUwTvDT+0asV6Q9WqFHyB
            uDuiGB2QBjZu73dt79A7ilLo0ERYcnpy25VEcwOtT4GNKDFi3h5TOA8/+hQqMmnr
            ayyOad3QxmS6F3l6atwG6eOVNuX/g8dW37/y8bhmzDoCVtcLkXDC6nee7sfnro6F
            0mYZcPWTSYfOzUUqiGGzl1kLEhZT4nNkzT1oHBeFzZieSmZUBsyAWungmKyZS+WT
            GGyftAaLPlZfs9Dqpvv6P8tbpDqti/lBh+veVn26clYKnJcwR6FewFhQ/Yh+o5r2
            WDHnrQznHMVOLaz2hlvedqtdfR8mdpMZK4YozGtoXWFc+B7SclqRAyN3vh9VzDHU
            ZgEJAhBwYy4J9nEzHm0jH2GoIcSQlEh+eVtQ0kaGctu5IYD33QEjF7Bs4yA0zj+y
            6uIHBMrBkV0rMurHc/PtDcf3iZILywVycUURzdGs7a3Q0U2BT3r5jwviwSMfx13X
            A0pgUhztBQ==
            =Rh0A
            -----END PGP MESSAGE-----
          fp: 4C8C1857C468123F57E5C7E7A05D361B64156AA7
    unencrypted_suffix: _unencrypted
    version: 3.11.0
