apiVersion: ENC[AES256_GCM,data:srI=,iv:9mcnoLzA/x7vPfaXCTD9ACrdxYlme5IYg0WB/hZKU1Y=,tag:icYHjYLoi/8hT7hoDir8GA==,type:str]
kind: ENC[AES256_GCM,data:HBTmXfD+,iv:PuLC+xVpQTeXlX8PEDnwSK+6qXoO1FhO1u82sxxVplk=,tag:Jf8j3o/Y5kw71sTxE5YQiA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QbOKeg+RV1FHkcpqX0uuQw==,iv:ycAQpsXF7dcCOPa6CRJOjc8ZJbsMunEeXX+z/4aWsjU=,tag:MbYuSXGEtPS7e6jk/WtUZA==,type:str]
    namespace: ENC[AES256_GCM,data:M2t+SrnPZI9H,iv:JIeQWgPNCGoEj845luuLagE45t0YVBom2tJtbsUWHV4=,tag:IWV25CWI8g6cPIxh03EdUw==,type:str]
stringData:
    access-key: ENC[AES256_GCM,data:Yh+JTicGvJCiDp4euCB/yZTTa/SnzPK1Y5A4612ZA88=,iv:Vrt1SyccFi2MmtVA9re4hlFmc5ZTSdkioRVwbaqB/uY=,tag:3+ey4rIrjLy0Ai09E1ZPkw==,type:str]
    secret-key: ENC[AES256_GCM,data:ifCn2ySubgnBNK0Ww71BJDXxgFYOyTSwPoAI1A6XAFDaOJ5ex8QFtmqWEE1wx4S2gGnGTt01wgdmHPpPKgL+Yw==,iv:vVuz0fBNe1m+xeM4lAV+lPMc3xO+F8liL/txqWZ0QpY=,tag:nZ9NQVb8jDDgFjXduhChMA==,type:str]
sops:
    lastmodified: "2025-10-30T20:24:17Z"
    mac: ENC[AES256_GCM,data:7Gtooc/d3qlEbhKa1Kh7RUi+F8UYlqflDEjKZt1HX/4Rt2b7Po6E1mux1fZ4LmuKILSbi2qtWob4ty+BIj47+a75yceOTRLuEcCvK+h9GkZSfdWQijIY5xMsmgThEQrlmrLxSjt3BS2cSLk68yV+R1PXer4aMrbUVTm2sSznh2E=,iv:Fmc4BrKi+mB1mZq+54x7x9QodlAgZG2WSAdKT4q7I40=,tag:EgU2+O6LB8spNi+SM6lWHw==,type:str]
    pgp:
        - created_at: "2025-10-30T20:24:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2aYMUUzTqIRAQ//XBLN8EXjUGJeliWAtzrwB8QSWgagsD2/ndz0NRZ+FpLR
            dwpvbOvXcawvQw9vGda0/KRf2UMtBeUaowGYDRtyQcnPIUEuBj8khukyoRYBEPwb
            y6t6znzzpVHtDz49sCSI4DJbq3Bs/Z+Q4SOlfG8Phx7qT80W5hXorxLJTG9HDGV0
            HcfEUj4llX9fdnMCNfuJLXEWILLBY1oNVfo70mNdlW3eC2JGlK3YYRONNbCsQzYq
            htxuhCjAO3t3wzi40AUbUCd/171a/Nl3DXS+irF1BHmBZpkQ7C3idbc2hyZ3+e40
            giiR3NPEi0e2zOXUy1vX74V+yVzqEVWr+b1qJneZ8B4+zi8WM1ftJ6e9tzVM4oAn
            EKqnolH/c3W2eZSZVXGbIzcie+H8UyrDQEtm3q78kbP8eCytmrEjIa4qNOvHEAXY
            PFzqaoRxdunVWO5x+GNuacvPpiqfQ3Z0tJNauAvvxrfvTmt8j2RGj7XvFKX/YLaD
            y8ZB+wxWY+G75rQCrPuMdkM9gkn+N/F6v0ro3+qZ5fR2YAaPmlSllHRvby+xsE4S
            E4pCoD6YfG117Z5876RjNg0C8FG2XCVoR801TC7dXN+6J5SC40rQcnZLYPJOwlR7
            CNnYeYonOGspyHhki3fqN13FGEt1jU9AGavryv36lqwRM459/BBZr4Kkj1iEeY7U
            WwEJAhCgB9zvlRWUJrrfhbawHjcmEJofsvMTZc+HFVKO8EXhLuJuDEwSKMB536U6
            evbphL4x4talXFtA7Mb5AlD6kSb05GuWFP5CtXAs7gmThmfTrADFq6yLkGM=
            =cYdA
            -----END PGP MESSAGE-----
          fp: 4C8C1857C468123F57E5C7E7A05D361B64156AA7
    unencrypted_suffix: _unencrypted
    version: 3.11.0
