apiVersion: ENC[AES256_GCM,data:fbY=,iv:+6DOTODXVBJhdkgiwh6psNxt2dNeh8VCyDPhbavQH7c=,tag:K3MCK77xKs+NlYBxcsOGpA==,type:str]
kind: ENC[AES256_GCM,data:0NEy5w48,iv:8oLJVozFor/XoGWuOLADeDEQq42KrN24+TcNKGDtvck=,tag:6IryhqSo1SGuG/f3j27CIA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:E2qcyrhxoy7dcmSDg0rMow==,iv:8TvM10qVkrSweDicqyHglV519PwhgsUizlOcMULl/YM=,tag:GAVN/Od9NOR4rQsPVWtfNQ==,type:str]
    namespace: ENC[AES256_GCM,data:nRMxwOLdloi8,iv:cHBloC7yBZWoYqmcF0/l6yXH3at5XtqZfpz7V+Cx0rg=,tag:0zdcJGsC9ahawG/OGB/3VA==,type:str]
stringData:
    access-key: ENC[AES256_GCM,data:ra4YQ3UQgtDBz42He4vtExmZv3NMAM06vPi5gYpTPiw=,iv:HQ8+Bv2pufnLwJ0L8h1tJqmdF5lwE8Zpk75sfBi7VOQ=,tag:nOpQSYFftC4HPY0tzP5pkw==,type:str]
    secret-key: ENC[AES256_GCM,data:036mqeVN3yN6jUM08IlRZxBBbX/NOrLPueJJscxOBhDHDdNyQLvdXd5pbwdsLg7gjboNjI3i11f4Zo5mKWbtNQ==,iv:mnC69kd7CY5QBVlzthkzSA14tBn+Qt1uoOvJIXg6Q/w=,tag:wjrnypboRJCibXi5uOPmmw==,type:str]
sops:
    lastmodified: "2026-03-02T21:45:08Z"
    mac: ENC[AES256_GCM,data:xPQ4pdZl2VjjRpeaRlKB3CDG40Uq2gnMnNEKeA2j2EdoZ16FTpJlXV81qXKa/+00DzN1+9IdM9hbbzfsffImYbx+F94Vk2C113E+InqDFTSBgNWVOtM+U4pPVsAa5rrKM1rjub/I+gK6xirIgFeJjyV5+DJNX/Smn/5d0xFNOrg=,iv:RzWK8UqTNEM85xSwP2wci2OnGpK7Hep8olPRPZS2Ar4=,tag:/sepNFmMqaxTASXnqe9SPQ==,type:str]
    pgp:
        - created_at: "2026-03-02T21:45:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2aYMUUzTqIRARAA5VEGo4HJ7qFItfVh5yrb0MCtUG2WOsSWSZvIUKDsck6h
            DUtOZ4ECliGAGLNaVPtYf8XNFSZS9A2AUcJtaYhYx+GEZAodTShRJV9/LgxFOo7/
            cuchhZESi/u0+XUzk2eC1vJXkq/00Ns07aAvQBlutIuNGSvBhrGy/kfvKtgbWw+/
            E4K3kamSHTz3mrnfTZeNucgRpaz6Qr7hfcsn/YVMMsFnWd9MnzYQj2bwpIE9P3Fd
            g6vOSWir8wr/fhW/D8bP4KxpviTq/WbD5n4OAbuwQQbi9SAWT7hkIXLOaQ1YfQZo
            yy907zPwWgwi5+ZrdAy3AOvCsl7mh04ZPfA9ZzB7zDZPCaoTMzr4+eTRqEiJJ+KE
            LpDGd2yKbAAGqN2Q6JSo6kytao90ADLZBfhOwMSmTsJdaWOHc/1w2oi6V7Lir8K/
            7LajNbPDHFJ5fP49MG0yVqau1cam8kTJMOQHsF0uVEGanr0bj1TF5qI7VdAl4Ar3
            mYM2VZ6rEMHXjkMb4WnPS+sxjrPWC/Vu0xkSAjbyeRJmo73mD/m5hOvEyQ17hlVy
            xl07xHwu1oWMFt/MCqYXCbm5tSo3kwMJU1EWApgKtvJ21WQgYfWGE+T20mmrlcAd
            f+BdY5UZO4ejvufvILuAoU+SwSNFug0K184URaKBRhrNPH8zaAVpn+wWL93Ka0PU
            aAEJAhB8xztiwNipODRWHGwLcQCzCJPIYvLujs3C1qhwvLDNfHZH7FXu3AiNqY3p
            X5qRXU+B0L/ZEKU9DIXdAfZUu7gmTxlL7YecopBdCweaynq/ZXXLx38pmGIPGdWU
            MSFWPFn/7vEg
            =PGhU
            -----END PGP MESSAGE-----
          fp: 4C8C1857C468123F57E5C7E7A05D361B64156AA7
    unencrypted_suffix: _unencrypted
    version: 3.11.0
