---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-oauth
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: kured-shoutrrr
    kind: ClusterSecretStore
  data:
  - secretKey: url
    remoteRef:
      key: "b830888e-a946-4d40-943c-b1d300a0ceeb"
