---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kured-shoutrrr
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: url
    remoteRef:
      key: "TODO"
