---
apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry-collector
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: opentelemetry
  namespace: opentelemetry-collector
spec:
  interval: 5m0s
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-collector
  namespace: opentelemetry-collector
spec:
  chart:
    spec:
      chart: opentelemetry-collector
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: opentelemetry-collector
      version: "0.138.0"
  interval: 30m0s
  timeout: 10m0s
  releaseName: opentelemetry-collector
  test:
    enable: true
    ignoreFailures: false
  driftDetection:
    mode: enabled
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
      strategy: uninstall
      remediateLastFailure: true
  values:
    mode: deployment
    image:
      repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s
    command:
      name: otelcol-k8s
