---
apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 5m0s
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  chart:
    spec:
      chart: tailscale-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
      version: "1.94.2"
  interval: 30m0s
  timeout: 10m0s
  releaseName: tailscale-operator
  test:
    enable: true
    ignoreFailures: false
  driftDetection:
    mode: enabled
  install:
    crds: CreateReplace
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
      strategy: rollback
      remediateLastFailure: true
  values:
    apiServerProxyConfig:
      mode: "noauth"
  valuesFrom:
  - kind: Secret
    name: tailscale-oauth
    valuesKey: clientId
    targetPath: oauth.clientId
  - kind: Secret
    name: tailscale-oauth
    valuesKey: clientSecret
    targetPath: oauth.clientSecret
