apiVersion: ENC[AES256_GCM,data:vhM=,iv:zfznv7V1ntQOQOeGpnBSP1igBLCRbji+oUVdXgk177g=,tag:qTXvFrDB4wN3/PtJEqS/LQ==,type:str]
kind: ENC[AES256_GCM,data:c7DinUzx,iv:G5MZeULo/DXbjN3oH3gdoa31Uk5ZzcsRg3vwA+z/ZkU=,tag:8vz0JdBZ6rOZzhxqsBPvJA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:B5Q/FiZr,iv:I9Wjxb+mvJdWbsHp8H/OTdqyqJkimuvKvw/RYCws22k=,tag:9PmmIYbXwAVgf8mSO6FcOA==,type:str]
    namespace: ENC[AES256_GCM,data:Rzo8tAMX,iv:EyV0DGgDbMWr+zz9CxfsvvEsnw+3x2TuCs+fdEfcFqE=,tag:g3U8qu0KlH0ds9a5ESTQrQ==,type:str]
stringData:
    client_id: ENC[AES256_GCM,data:WueDH2/w,iv:Rz1XImlDivEZ881df9iGODdQl+XqMBjKe51cfunkio4=,tag:Zole9IhGcdewxD+anIwWAA==,type:str]
    client_secret: ENC[AES256_GCM,data:bRuE2Fk4,iv:g45DICjPQ9v2p0HwqlLgmu0LLHM8V/pnlR4yCCZHs6s=,tag:F5k/wLdqBbJbikBhNIVMTg==,type:str]
sops:
    lastmodified: "2026-01-05T19:30:41Z"
    mac: ENC[AES256_GCM,data:fo4FdcdErWUeDiz7Yg3KPftwY8hc0KiZez3YLV2nEBGVmACXsdpJOI/h7msJbU3lF02nTuJv4ZGSTuSWf+bJbOPteJDTRKoJqKlUpKD5UbgDMyxQvbY5Z3Kf1ISwUPxH6pq6FzF4RAGgK8kpFMKGqCsxyO6ODgi3dy4MhQxVmGI=,iv:yYteEwi1iL7DNO3T3DHqRJzTurYjDwZ1dpVSfjNIUhE=,tag:rexpKJLBq9KCvk33mFyzDg==,type:str]
    pgp:
        - created_at: "2026-01-05T19:30:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2aYMUUzTqIRARAAiIBPgg+9u+DWtGmoQtNypmezzkpHXqzbTeKloCrCFDgA
            fMG/HComk8Cxgq7O4UX8WPA/Tm/41S5yq+HpZYsnxxJgvE/rIJvUwAVK7mo1vNZY
            XAh30Pr7VGJ+7rsPmyCMGzcfYy5S/EpIv441Ux8Jok+PHQkkn+CnPLyLGs37rpk8
            qDxB8FOB4EEmY5mc6rwSY+SznNJVzqjch9OudNXH3Yq96KUQ6/uMA3or3yd9EdbK
            7x3rUy7FUm8ETYcoqqopKa6l9R12mCtFWTVwVmH6p+w0AbNH87pn76npQGoEbyX6
            zbNXk1nS2ICGTGXxCg6mZSgbZbiffheM0v9eOIO2xNO1OCmV83vVhb4FrOwxSRSC
            F8iAzZSwttMsGqOIJpNMpkJfVRcKRMPC+LgFio90tFpz6gM6c4CmPhKdRvUfp0gw
            YNiF043Xn+mEoxImY40lKSYt9mMLh7x1P3AAYHE7LInp4d8FrL6knEXDydBlMsK7
            G9vOa7ibcy/WxlP23/jW/Wilhs+zzWpzVJDuSuKQwC1OGsoif2hnWoXA1qbf9Utt
            svut383BdApSFrPyEc5+rrbaylkpblkw13L7z2DvGoNIgHJSLE8RRnXRV+zlLczn
            zRYpwN3W3k3vur2QVEX5OMAwMfaUZr4QCH+xwY8Y0yKeeSH+8KiK8yyrJvLEiw7U
            aAEJAhAEI92eh5gpvnwi2+SACf6ZE3JpLY0tNLQ3uGJ8JC2cwJ7pBTAX05/ByrZR
            BznQn9r35lnY+YxLFBUcESyiaKoWLofal7trTtW8iuysWjjxIHHJ394rGzE2l4HA
            kogGZQHeMrqO
            =185B
            -----END PGP MESSAGE-----
          fp: 4C8C1857C468123F57E5C7E7A05D361B64156AA7
    unencrypted_suffix: _unencrypted
    version: 3.11.0
