apiVersion: ENC[AES256_GCM,data:Uv0=,iv:ndiD4ccEAX+5hDs2SsVnpB3Z44g3llATZn7138sZgR4=,tag:MucF244UmOLG51NxFZI5+g==,type:str]
kind: ENC[AES256_GCM,data:JBH1JzTt,iv:slRyteHroJ426Dv6vFAJ4akycfM7Hr2qC+TwQuUcgWQ=,tag:1hHH6asc/Z7dEY1M7MZRRg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jVakJVZu,iv:gFyJ93O+REBGjj5WP/3lDD39HkyXAQBR+CVPXKFCJ1E=,tag:9urr66HN4k8HJ3KZLGMl/Q==,type:str]
    namespace: ENC[AES256_GCM,data:y04zdMZO,iv:5jdttWPRWOAbkhS5V1csJcDb8U24jYp4fssmRZfoQVM=,tag:qB0c5A8oIrBFamefaeDxeA==,type:str]
stringData:
    client_id: ENC[AES256_GCM,data:oK1AFehz,iv:F16TeWtXCq6ZklftL6Y0b7RlhOLvYpft453CjqM8mKk=,tag:uintOITeIX/Er0RIqcQr8w==,type:str]
    client_secret: ENC[AES256_GCM,data:H+Xn3YfW,iv:iJKX/BoSELMI+hVSPzTPGi/UINX3MCrCxcs1zmpu/O0=,tag:0Qhp/AjwDYGBcwDPWMRovQ==,type:str]
sops:
    lastmodified: "2026-03-02T21:45:08Z"
    mac: ENC[AES256_GCM,data:eO2P7NZlQYm2TbMeKWB8eDdIKusAoudNNWD0526OTB1P4O3sCT2zkLvofD/ehmRpVf2poY5vqE7TYZ35/Ejf0C88g1sB5NFitNmtBIpLibHr/GCqYEshfWfV+c2FofW58qzFvmAVJo2Q3tndW95Ol+5U3+meRp6N0nSsgUkOKUE=,iv:o72lN14MVukOjaiZDBGnj7d/46YqbSOYiCLqxdaWaow=,tag:18KvT+g7ImORVrwZ4qCRjg==,type:str]
    pgp:
        - created_at: "2026-03-02T21:45:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2aYMUUzTqIRARAA25ktdF20FeCVhBC8Bk2I3giqrbnAptquP20851mfdw8D
            /3N1qqRLDBGFgxXuCi+wecxnOoWpFyqqJxwUZfwB4O2DLvIlw4lmlP2b6epRmWMB
            4eUnr1jd8Hje54E60faWVKCpblvtwErRt++TzC2uU8LAwLxS1zzcCtoFxz4gbcXC
            renNafQ41l/Vmt7Gs2QozMO83kzwBuYimx+OdQdSPQ3VPbCd8VWSvBorw2CukZO8
            3dn/aIXPZa1ztHmQ1pGkLUiJF3OZfL14jVkMEBRjcfOuC9D3F+hmWag5QZJMy/s4
            H80ugseICMfYLg+auSFTg3HsycUrnQnO7dRkJbKaWl6uU/Ef7RtAYNVQt4RVG8qr
            lnlAy1waisXAVhMB3I4yz8hMGrDkbFt5vH2DRG7A6Jz480dFKH3qMjftbCHu7xEd
            A7PuRXufjLz1pdMw6HoBTQsrN292ffe4QTikXxBC5ekoF4a5hq3n91MQfqCAeD0b
            +FlfXwjV1bjwly7cjdCvFeQR4R6YJ0UX2gkLaGUtQrDaT3j0F0qSJmqwPXwdJKbo
            7Eu75EpQkz+nUNuus5acwPzPRS4kaCQnLCwD3IX5oUV9tXqDmxUz5oRM8rN0LyEl
            ATdg6/99I52v+8AX/WhN52rr/aDLvdnqwvL6BbIa9xuh4YqzeqntoiHwFhrq1FXU
            aAEJAhB4v2hHCrxf0YalFZIVi5pJNzCgdILZMr9fMY2AIz3kDoVe7Tu5Rs726m4C
            GXs4F4zJs24GzCuZFTF0fYAAHUxpfJ7duJcY/K2SmX0Kxe5c6LdL8fk3THX5X6f4
            Nxw5MA0ZrUol
            =/2LE
            -----END PGP MESSAGE-----
          fp: 4C8C1857C468123F57E5C7E7A05D361B64156AA7
    unencrypted_suffix: _unencrypted
    version: 3.11.0
