apiVersion: ENC[AES256_GCM,data:GJs=,iv:ihyZTlUxJ4Aizv63ER8LpvUqLWBsvJ0odEGoLg0CIrU=,tag:IjA0SEUSf9COfpOeoI9uqQ==,type:str]
kind: ENC[AES256_GCM,data:gGbi9jXR,iv:S7PHgIBWtlbTgOnn6wUsxU7vD8QDAxQarHuQ7QXHcVo=,tag:7ypK/GcryMfcupvF6bJTVA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Wnu6/5EwtvTRflzpJ9Ld,iv:EqCSbhIKjQxQgxhN63hXzHq3o3pRMa8LLCb7ahxhaBw=,tag:tH/eWSvQJlF/egMEf4kBcw==,type:str]
    namespace: ENC[AES256_GCM,data:GHJvHnSdXtlO,iv:03EvinMTTv9lFv4ljWUFMAQOKOCyyRJaJeTbeCXSwE0=,tag:PwwOR6lkxIz2MZQSf4R1+A==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:ZGkvCnxgMqacO/0V0xpf6Mo=,iv:wQPnnJCOGTJH3EvlarcJjrh3AgUaYrzqEoAbuPlf1OE=,tag:gaEDB+p7DcpApgwlgci16w==,type:str]
    clientSecret: ENC[AES256_GCM,data:g6jzu/impcLqWNSwvVBYgz/cSOujTG9adyMVbjHlsJl7YPkTXhMcX8eSLZgCuPhiFY0+V59qvcFr3qaAsSwz,iv:mFVXSMzIsK/zHkpb9guB4usKqqUC9rrT12bWJsHYF8A=,tag:EkfES9KB4bKlIGfc7rNh+w==,type:str]
sops:
    lastmodified: "2026-01-06T10:45:27Z"
    mac: ENC[AES256_GCM,data:Fmx0mnL9xCczIj0NeIfF+vntqglxnvXRdNBUo6HehuYJai36/c0p7Rp6VxiUeZC/kHM+yB9mmM+THbxZR7g/9S10UztevDCAx3unlKLCwlAuOrzQ/w9TU+d13sUW4QVGiWgVU7WnXPL3iQp2SPJybWR+vrQD5pySBCmLphbZ4ZU=,iv:Qc3uMKt+xBW/bGOh+yd6rms0IhMQNr3Y+ImYKCLCseI=,tag:sSxV7Y27IkI4BHSjLIzKXQ==,type:str]
    pgp:
        - created_at: "2026-01-06T10:45:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2aYMUUzTqIRARAAyf4QfJPHO09/ZndH38/c+pSvnnd+rkrU6iBPDYqJlL3i
            USD8p7GbkbtKFddJy98gwn4TRvnVH05ihjE1TVt336HyqeUfLusXOneyqVNhtMms
            UUAmGSKKOo8c0KJq0ZVzd6AFlkJwhrsh2dvclbfCWIAH9TwIlxQoYVaVs5SOcjC7
            pDWbFZOeLDg8sbtlkRywD6Jz5EFHFCklSNWErnpANzyrU4ugSc/ZA85ZAwR4rU4O
            Fj6NQXPop6t49Ger9zVVElFxu/U+mwcl8SGQPywS6s+RKJRzgLKK4q/vosFpRKWd
            K4id4b9pkbNTVpKJmcn6GsPcpWqy3P6nkZAo4FBeV9A1LcK0dAsPAPPQ9IhJ3y93
            4s43iBpWR/vJ3QG0tcdHr7AFnrO18NBDEq8XvL8JJrTm2z0QrjsYej+eoYsR3gcc
            KVm9o6qx9L4ZueL4AkifWTrYtqAYJszLCFyj0SweWK66yEEx9BXBpxGh/0GRvRda
            +ouR2YNXl0XCOz3yzHYNBMPknqwVxmyv0+vFOrmtFuLAT8YR7UmAKLg+XhiTYO2e
            ggblwTlUa8KXDRAkvfiXchmCsj9HH0gBYUkPFjEOl3OrS6x0wmgJZT/cRZJp1n1M
            dqLM1mxQS4aNSle3CMNIwzGF5ZXP9KXNb98VLFZleroVWTguoRQZHaRxn28sZ4bU
            ZgEJAhBVxGVON2x3kCPBH/s+DwwdSlEkHGY6ESv5OHoPhOVQuybAeVMQGryKCHil
            +JMmCKjUNvZL2+yqGN6vRqppqGHFQa5EIgmsp7P90jwkErikEX8AONkw5wdHPirn
            SZvwqEPmoA==
            =8o1w
            -----END PGP MESSAGE-----
          fp: 4C8C1857C468123F57E5C7E7A05D361B64156AA7
    unencrypted_suffix: _unencrypted
    version: 3.11.0
