apiVersion: ENC[AES256_GCM,data:6ks=,iv:CGPCeiMn7l5HWuuW2yrAaQeuFiN60CKBlf0xWp3aOUQ=,tag:+ALkolgTQNFAMAd6w8WWLg==,type:str]
kind: ENC[AES256_GCM,data:qnw+i934,iv:MBhst2LjT0AQWFg1xtYLVr5Lpb3xkqDFnyPu+tFYvCM=,tag:1WgVAwF/Tm1oZNP/iDRqGQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hQH8MP/FbpCtdSK07p+C,iv:9vABBYKmd1X/6/yhY7tduMna5AMW22pNYUs2g9ooGU8=,tag:yF/kuvpOEcJ8lOM5zOzL0A==,type:str]
    namespace: ENC[AES256_GCM,data:X6LSLLwnx+l6,iv:lI57Sc2JBwzvt8dD/dyUGd8dNXxR50g7zkvDoTvLhRY=,tag:+pE0mdJGKQWpT1cTyCfVmg==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:qc2jbDLRROcia4gmot/iJ1s=,iv:4+OmxA7NPtTO8dy3z3gVcw7R8dnfcjoTHsMsQeHjeBU=,tag:d/9u+J66vWs+Fex75T/I5A==,type:str]
    clientSecret: ENC[AES256_GCM,data:/ExeMxZaue4Di8fwpudJLc7qN9us2TUUpqaDh1oi1vtWwABAoY9lL289mFnj/D9pNC1RmiJm0Q4ebbpobVTR,iv:oKIIrTzBY8RCAqkDbI8vORhKo6r98sl8wGukcL7on6s=,tag:8ANMn9m0Mnz2QFO7qRhv7Q==,type:str]
sops:
    lastmodified: "2026-01-06T21:25:17Z"
    mac: ENC[AES256_GCM,data:7ZDifrR949z8EBozd3NlenztuidIf3vYCpsGDiTR1pVjC74z5mEgP2+6l67jWPSTs/qskixCHpq7UfBHi1PKVBCaVR2IVCJjYtZikeiihnHY4f0g6YcRUexY1YzVv7zqr10NSuZweDmJaDCB5KvxmdrjNXSIMoRJ5eFVs94XhLI=,iv:EAVsHUKXBTtrfBQ2REKa8U5yltk67LMqXdBWx0H1A58=,tag:Tl/iafcL7zCf/cNnBcfz3g==,type:str]
    pgp:
        - created_at: "2026-01-06T21:25:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2aYMUUzTqIRARAAnERaMtj4ajD/bcFekZOmfrUjuqhV/yNQuqNmxtS2jI//
            DA7CX7Tc+w4D5bO2hN+Lsr1+9hLzZ+9ivL9YK56ZhNzBGCq1x2sJHSXpK4+BLL1r
            WanuVOkiMmABpTsOKGHRP/rIexsZrXZccE3KMIybR5KOddPeF+e+l6FAww1KFu0y
            3kyXj3S88Jp5xD5Ef3fEUkdSAj/eOXkD+yVkcauH7ZrEnSqVXMSUHppFzGxFdj74
            HOsln983JaY41WFU5Z12/Idxfy3fjbfzls+3G1k7KccQ55qPd29YtAZEawzzk7xT
            gdsZ2m9tVKbW/mBe9grJWkag0TFukSVG4b7WrJAERaHEtQtMdDRephzExVAQ5YsH
            D+npykOFNPLl4FZRhR2xV65txLEYJpoxqIkEt1DJgmSXphDs4SRriBUAIKx8WGjX
            3PvdUtXgKUg30b0HPbQX6fOvlYnU2UnhACnuVntBdVbRZ/JUYwfF1Jj1SyBFw+Ul
            uS4vOeKOyLQL/QUdobJUB5lHzZ8f3PofLHeoVZmEInLaAylgI1TakT/kBmzsWKNv
            TSOzNlWeDkl6skzwZHO8J9hb/Jc+z3z7eICbWaahLoqOPbRaTgJwomWnGRcGQlZm
            1UrFWjq/r7HEBDndA8iokzO6Te8BUsseeJPmLais9e55OD+yLs2FW3DE+yZfWt7U
            aAEJAhDAKo/Ec55GI/NqQXwEtO993BcDuyym9MInn0q9nM3YUR8DUlLgVdSwdwP5
            z3/877xDB5i61onmai1Z9dHQXQyHXlHdQfHQFpx3LNa6+ZaPXGSHA+owNU7AdNqy
            nXcYaWqUcvad
            =8Gpr
            -----END PGP MESSAGE-----
          fp: 4C8C1857C468123F57E5C7E7A05D361B64156AA7
    unencrypted_suffix: _unencrypted
    version: 3.11.0
