apiVersion: ENC[AES256_GCM,data:dK8=,iv:Q285dKJgJTIKdea3Btu+JdGw4Iv1cQag/XoDEhgCNNQ=,tag:cH41lfqQCMItl8UeUP20Gg==,type:str]
kind: ENC[AES256_GCM,data:0TSVlLEF,iv:jTRV4oGp94l0GhMdi9MXrsb/umrpOXxmHwdqSXE24/s=,tag:70o4lwoOvMguHvm6IOaV7g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HgfwW8ae8DbTy9vvQWyt,iv:6eZW5VR4M/+qHChG0ksPUhK2BwVZOgkEtY007rTWCDo=,tag:wDlS2atleEki5PiuYWn2EQ==,type:str]
    namespace: ENC[AES256_GCM,data:WNAn6mQqJ3rX,iv:sg7yq8O5D5qOtFXQuuGFfmogSEh3MgwrGMR9GW9lNnY=,tag:G72Ka7l+H6Ug9Rc8vFqTVA==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:tofskc5VV0SjG8KRu0JjnhU=,iv:iUVNlm8GZ92/nQ4mKvBVwsMQONhTsssxO70oAjIwYNM=,tag:Uc3cUCYZLqVw86mLwvyEQA==,type:str]
    clientSecret: ENC[AES256_GCM,data:Kf5nakPFqJxxbPkdEQxgJjzcv+r6wYPR5KP9+HHSVD2podENAjiXJOaBRtXerfcOldOhWvMwPatAOKOsrRlx,iv:EkikAqC+IPhvOsogJ4/sg9sv08L0QRh5Zd9wJQ3+fdY=,tag:UbO0zpaOMeQXnNExVr8Tow==,type:str]
sops:
    lastmodified: "2026-03-02T21:45:08Z"
    mac: ENC[AES256_GCM,data:xQgjK37Lw7SoEOfBO0S356ThesPc2tTm4uU4v46VZfQgNNVjwQVIvy9iWGxxQ3/7JMtNM9v/wcndNIavuLbyhSvluJgWmvxfybNfbYj4SynkCG00/jNg53di1bTU7lP3LOXLBKk844w3pHUUAtdq7+XRBRuW2vgx34yqyiUg/vA=,iv:n7Rcz8pVDypnbME4otY0SAqJOU7Ezq4JgfES5z4eduk=,tag:WmdPD8gSZhMVCuyGfn0N+A==,type:str]
    pgp:
        - created_at: "2026-03-02T21:45:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2aYMUUzTqIRARAAzVElYS/uBrka4S8cd5yvgbdArP/nHssBD+tj133ecTdT
            d+HCfs/0Ok+PvWoeGOvAHglDz3TvcZvztxHfZyO8FlAWcdJpoTbROqqtWW99CHA/
            xYySRHR8xOxh9YyK/LEATqxwoHVAdNt47s5weMLH6bQQHxusMBT5LhB5V2r8zI4t
            xbty9cTPmXE2mNlwreVKbo55tbSbXhyqnoWSiwPAod92sBaH5tv4JgUFuB6xGrk2
            63dbtbk0jSaGueaKtQRaqOuXliOsq9NpxD0Cfp0jFjyPMDABk0oflcTSCNeIwiDt
            Tqb7PDT+90ixrro8Sf1KEZ5rKaF+G35mGPHOSrnNiYHTP6RI6tR+XQlH9/wtaGPw
            k7IKXthX5SL/Wjr4Jlg+7LJTebkyu06FQZRi1zBwzqdWfnHUiYOAUPa7ZjgQllF3
            gnK7m7aKp3fdsdcWuf8W+LbWqOPIotl2M97gsWlL4fHIS/2r58ifCMqtjhuB85MA
            0pTwraHLUhkqT1gWYDPPr14YPceQd4rQqRnytEcUIvmr5ZSk9u6BsZXXuihZmOeI
            MdGSlRvL7eAOEVyEeSocq4m+DW/QxTL6D1BbXcyMCpDRSCrZ/lhpJHUMq/pLrPnK
            jhZUHc2aOytx+/lTAjHHTxnhoEWHj6W1pxrM574C1JoOhvJSEbgbLA5ipQyW8QPU
            aAEJAhACBF2/5DHEi64+k6HYg5c/oeWcNLJNwXEs8Xc2eXUXEqYGM3Oog4dy2Z7Z
            HlCPUIbkfJsTkKEUwe+KX7t7s5cSTTHTd6gj9rlf4XewEKAigmVs7Hb2tslTlU4n
            6U7lPEarQ9cx
            =C+6S
            -----END PGP MESSAGE-----
          fp: 4C8C1857C468123F57E5C7E7A05D361B64156AA7
    unencrypted_suffix: _unencrypted
    version: 3.11.0
