---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack-dependencies
  labels:
    override-target-namespace: 'true'
spec:
  path: "./flux/apps/observability/kube-prometheus-stack/dependencies"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack-app
  labels:
    override-target-namespace: 'true'
spec:
  path: "./flux/apps/observability/kube-prometheus-stack/app"
  dependsOn:
  - name: kube-prometheus-stack-dependencies
  - name: tailscale-app
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: perses-app
  labels:
    override-target-namespace: 'true'
spec:
  path: "./flux/apps/observability/perses/app"
  dependsOn:
  - name: tailscale-app
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: opentelemetry-collector-app
  labels:
    override-target-namespace: 'true'
spec:
  path: "./flux/apps/observability/opentelemetry-collector/app"
  dependsOn:
  - name: tailscale-app
