---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-app
  labels:
    override-target-namespace: 'true'
spec:
  path: "./flux/apps/platform/cert-manager/app"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-dependencies
  labels:
    override-target-namespace: 'true'
spec:
  path: "./flux/apps/platform/tailscale/dependencies"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-app
  labels:
    override-target-namespace: 'true'
spec:
  path: "./flux/apps/platform/tailscale/app"
  dependsOn:
  - name: tailscale-dependencies
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-app
  labels:
    override-target-namespace: 'true'
spec:
  path: "./flux/apps/platform/longhorn/app"
