---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pocket-id-dependencies
  labels:
    override-target-namespace: 'true'
spec:
  path: "./flux/apps/infra/pocket-id/dependencies"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pocket-id-app
  labels:
    override-target-namespace: 'true'
spec:
  path: "./flux/apps/infra/pocket-id/app"
  dependsOn:
  - name: pocket-id-dependencies
  - name: tailscale-app
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: registry-app
  labels:
    override-target-namespace: 'true'
spec:
  path: "./flux/apps/infra/registry/app"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-app
  labels:
    override-target-namespace: 'true'
spec:
  path: "./flux/apps/infra/forgejo/app"
