apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-apps
resources:
- ./apps-infra.yaml
- ./apps-observability.yaml
- ./apps-platform.yaml
- ./repos.yaml
- ./ns.yaml
patches:
- path: ./patches/common-patch.yaml
  target:
    group: kustomize.toolkit.fluxcd.io
    version: v1
    kind: Kustomization
- path: ./patches/infra-patch.yaml
  target:
    group: kustomize.toolkit.fluxcd.io
    version: v1
    kind: Kustomization
- path: ./patches/target-namespace-patch.yaml
  target:
    group: kustomize.toolkit.fluxcd.io
    version: v1
    kind: Kustomization
    labelSelector: 'override-target-namespace=true'
- path: ./patches/pocket-id-patch.yaml
  target:
    group: kustomize.toolkit.fluxcd.io
    version: v1
    kind: Kustomization
    name: pocket-id-app
- path: ./patches/kube-prometheus-stack-patch.yaml
  target:
    group: kustomize.toolkit.fluxcd.io
    version: v1
    kind: Kustomization
    name: kube-prometheus-stack-app
