---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack-app
  labels:
    source: helm
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-github-io-helm-charts
        namespace: placeholder
      version: "75.16.0"
  interval: 30m0s
  timeout: 10m0s
  releaseName: kube-prometheus-stack
  targetNamespace: kube-prometheus-stack
  test:
    enable: true
    ignoreFailures: true
  driftDetection:
    mode: enabled
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
      strategy: uninstall
      remediateLastFailure: true
  values:
    crds:
      enabled: true
    grafana:
      "grafana.ini":
        server:
          domain: grafana.tail4d421.ts.net
          root_url: https://grafana.tail4d421.ts.net
        "auth.generic_oauth":
          enabled: true
          name: Pocket ID
          auth_url: https://pocket-id.tail4d421.ts.net/authorize
          token_url: https://pocket-id.tail4d421.ts.net/api/oidc/token
          api_url: ""
          allow_sign_up: false
          auto_login: false
          scopes: openid profile email
          email_attribute_name: 'email:primary'
          skip_org_role_sync: true
      ingress:
        enabled: true
        ingressClassName: tailscale
        hosts:
          - grafana
        tls:
          - hosts:
              - grafana
    kubeEtcd:
      enabled: false
    prometheus:
      prometheusSpec:
        enableOTLPReceiver: true
        retention: 31d
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 100Gi
  valuesFrom:
  - kind: Secret
    name: grafana-oauth-credentials
    valuesKey: client_id
    targetPath: grafana.envRenderSecret.GF_AUTH_GENERIC_OAUTH_CLIENT_ID
  - kind: Secret
    name: grafana-oauth-credentials
    valuesKey: client_secret
    targetPath: grafana.envRenderSecret.GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
