---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack-app
  labels:
    source: helm
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-github-io-helm-charts
        namespace: placeholder
      version: "75.6.0"
  interval: 30m0s
  timeout: 10m0s
  releaseName: kube-prometheus-stack
  targetNamespace: kube-prometheus-stack
  test:
    enable: true
    ignoreFailures: true
  driftDetection:
    mode: enabled
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
      strategy: uninstall
      remediateLastFailure: true
  values:
    crds:
      enabled: true
      upgradeJob:
        enabled: true
        forceConflicts: true
    grafana:
      ingress:
        enabled: true
        ingressClassName: tailscale
        hosts:
          - grafana
        tls:
          - hosts:
              - grafana
    kubeEtcd:
      enabled: false
    prometheus:
      prometheusSpec:
        enableOTLPReceiver: true
        retention: 31d
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 100Gi
  valuesFrom:
    - kind: Secret
      name: grafana-values
