---
apiVersion: v1
kind: Namespace
metadata:
  name: calico-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: calico
  namespace: calico-system
spec:
  interval: 5m0s
  url: https://docs.tigera.io/calico/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calico
  namespace: calico-system
spec:
  chart:
    spec:
      chart: calico
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: calico
        namespace: calico-system
      version: "3.31.0"
  interval: 30m0s
  timeout: 10m0s
  releaseName: calico
  test:
    enable: true
    ignoreFailures: false
  driftDetection:
    mode: enabled
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
      strategy: rollback
      remediateLastFailure: true
  values: {}
