apiVersion: ENC[AES256_GCM,data:G1A=,iv:PLKriQqP0aCc9QbrvsU3bShyfP986RUcf54mjMQHufs=,tag:gTUTieFcH98ERz5GOmApeg==,type:str]
kind: ENC[AES256_GCM,data:p1uNsO3i,iv:Fy1LoMHQA4thXFz+jJwMDOmBP7ESsFyE7Lwl8h/0Cjs=,tag:JUrDOHecVF7iDQPClRbwfw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:oYvEYZDZAqFOovj5Bg0b,iv:/n+KYy7+GsNT4ctSOYzZzGQc+IoAM8JwEdzaogguCt4=,tag:8MgUS7Vs+n2+jXpT3UHV5w==,type:str]
    namespace: ENC[AES256_GCM,data:bfz8fk+Gamhp,iv:TR2vRv9TGyhixuPz6h2xMKGb0CY7MN7uVN7a46Zvn6E=,tag:0L7whGU0ExfMUont3BRD7A==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:Fu90HgmSKKQXwx8BPBN2tOE=,iv:S/koe0W6QfUXrt78tzticf/ZrCNU1geu/x7zN6873do=,tag:sCPmCo9AaCvSmTB3PgaytQ==,type:str]
    clientSecret: ENC[AES256_GCM,data:9pCPwzrtLJJP79VYnZJFLeVkf4YUWR+SWGF0TkirHNYV+17+EMlqDsvVDwal9cOiXEkx+kqIdFFDPBj5T/k4iw==,iv:ENsyDahfDKZpw+v+sYKObdovWKYGFB2yWk7JLVRy+FA=,tag:il5xW0ctbYPrSGI9ywvGmg==,type:str]
sops:
    lastmodified: "2026-03-02T21:45:08Z"
    mac: ENC[AES256_GCM,data:DIx16i3mrAtLc4ASOr0IBNyFR+/tli72HolU5x1WZknrW7C02IhnMCdDLE1C0ZomGFjVeRAzGIdrXxzf/MgLcboxZF+nT1wn7enpcAS/aw8sa9KH+vZbdIJCT/vl6S4WVoHas29U5r0In0C2rQ3cA+JEU0zZXcuEB45GfoyjfDo=,iv:NjrCqYYNchvWuXGKF9Z9uGI4KMH4nZ3vRQrZovjdVsQ=,tag:R41WMP6bh6At3R+GFrrWmw==,type:str]
    pgp:
        - created_at: "2026-03-02T21:45:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2aYMUUzTqIRARAAsI+ONfaax4IHv6FdmdBWCcqLgDISv51EV717TkAKOhBw
            Od7vLI2pMl8fUBgeXpOM88lo53wsa3jO1zcZ+FLl1VD30Yj00nPFy4zGgMM395sR
            2RfXFFLY36XzrBQ972UPwxV6HgHwfo3Pv880kIxNlsKh/q8Z+WqWKj23FYt9vlue
            GoCtXW62VjGTcdnr5NAjn9h2dRIGR6D2MGjnddLXFe4xRrjpw4avG6UYRwNrjpSh
            xlwUqbS1D2fR4N9djoR0X2vEKC8qV+a709CrXoKh1S/Ke1qh8HRf5keE0Kbq3S+F
            uYBkUxR8IFQi6oYbc+f5WLHYvh33v4Wn1zWQRFzAr838GjYLaYUhonQvFsaf4lAp
            xZAO60Z/WpMSUPFjFis6xw24PqcUCSxin9tar2k8mcFukKQWWovbIUo1Mt/MKOoj
            VroH5cfbhNtadAnjqt6ZnHnUixKrM+yNW1qieuN3n/Ozq+3shqQeHSz4qF11t9qz
            aJqNMAER2fvapsJ0Qw8Hl5e1BhCelIOK+4mZHVWLOTJ3l9FO2COGBo30zDsnLvAU
            ElHkZHHKehpyf0owQ23Bd4cKa1z10NjxEMziUIProwWv11IzRJ36A96MoUPR6pd/
            igLGLMc1OYvOdSoDiXJYN+qxZq8b2y4XzsThgss1RJ7yYunMBjX28iORtumylY3U
            aAEJAhD5EYIbt5tU7gnUaepc0HElsEEyt6gvxCqQgUiI3viOCLrt+iTlIl1FAnYr
            4EGXkLns5IRmCgpTp9LxYSTBIIdAlrR1plsirUK75nU9xf6Y4gCNTcYgVlCe397j
            FkXf57aXW0LR
            =3bZF
            -----END PGP MESSAGE-----
          fp: 4C8C1857C468123F57E5C7E7A05D361B64156AA7
    unencrypted_suffix: _unencrypted
    version: 3.11.0
