apiVersion: ENC[AES256_GCM,data:7iQ=,iv:PNjVFkCTNBGxA1yRb80uOf2rnCM1JqEKKUBwjfCPdKQ=,tag:duLxY+ha/aeaIqknMkrzDw==,type:str]
kind: ENC[AES256_GCM,data:t/43Ze55,iv:eOJl1yxYrsdZn3BUg95F8K3phrX8kJ/a6VRghhJDzkU=,tag:sApI6TUN7jGo1VH6JBMbhg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Sgk9bz3rXZXEEzMdCOhX,iv:wT2CQOxc2jEiSHJNPi02q3o0qDXTHwyQVUkUUjfXK+w=,tag:2LfPuj+kQdUIusemtaHu0Q==,type:str]
    namespace: ENC[AES256_GCM,data:pHoSt0SVIJBA,iv:UjsSY7AXSeYzICEJ9iqOb5eOPiRmgJjXLVDxsxYAdUk=,tag:HhudYv4E4qT3zawzrYoxDg==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:XhQ5dFQOu+/MZOgqSLmqEi8=,iv:EDnEx0K3DVH793YU91wK9UhHMrmhu5bjSNEE7o5Mu9c=,tag:dG9ka+v8UBM8xq0lKw5GHg==,type:str]
    clientSecret: ENC[AES256_GCM,data:z3l6tOnl6M6rMQ7TvML2axsEdkzvJcp4OB1yW5gEwoqhpXEfnBwS8g+83VVVpwJp+C2MkBytS2LpYtA8iL569g==,iv:74ySSoWM03hAzUmivmG5XPWNrrNoE/5Er8b5LPVJxAA=,tag:hpQGXUDejiO7BCiZkfQ1IQ==,type:str]
sops:
    lastmodified: "2026-01-06T18:09:17Z"
    mac: ENC[AES256_GCM,data:d/xwcu6p308aOWrOgvZh/BQkvEX9UBNfbigqvg6/P2FZkMPPhPpGVWkvkiw6uHfMqwiYDqaZTJEpVTHTTTpCPovcU/3O3vkXlWMyTJ4cwDH/wtSXcun+x2JlYezwaumbobfUB4flwSEj8QGRBfO8cb8euAjbDRSB7eMhxkHPSjA=,iv:a5M+YkohhxllJzp4iKtetJuyw2Roz7lNA4dAdoEH1b0=,tag:ODR94GPMIN5xwNCcLXBDRQ==,type:str]
    pgp:
        - created_at: "2026-01-06T18:09:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2aYMUUzTqIRAQ/+KBwthE7KdTAE1YdwYJ4lSZi25lBlQeHOZwV6WYgehCg2
            SAvI4ow63aor5a3F5QBB5TVRxdMhf5Mhehh9iNhtS/QQXzY2he8xBA3cOF0rv59X
            u8hNDP/BVD3J9R0rEzTapasq0L5cGcgag38wdGQKZZlZMPtdh3UTAiYj7OWDzz0P
            ACupD7z64tzXyK79enhKHItdFPmKTtiL4PiZh3FT+zn9GrE9L0TrNKAJnmoqyeGZ
            X7TJ1I2aLKHziHuustJQhEDki6uMddBXNjDsjqARRINSHVwic4DZQ+euMD4d56HK
            5WFKMtyBzoHY+pWZ/Ry/u65pS8aYBMa5cKgf74uJn2Yb1Jyu/RV/6ePA2EVgUKt9
            SWaY3u5YcgcAfYwjWAxljQ3u3xwDCePeCnWMNSXydBwu8CsohUfxU3FMIEydvB25
            Ho7SmMcXlm/XYZzQpPFJgcEpDoZB5xqgiz2mebfP8cBF7tIC8EREBuJj4zt3I1S1
            IX1Z6iakrPhGnXG3j2KeF1gPiki/e1QnzPvZBl2BhwgnA/k1IsurlVOLQwyMRKf9
            0jtdMlYOzXhTpCvFeqolPtddwhL1xD/2YpV37LYUkc7gsOwHcKoIgGgjkcYqFQDs
            Xinsg+pmUA3YjY8IDkoQbx4DYxeReQ2lsD47uYt+/qmL0AiXdW+CWwe9lfnyuafU
            ZgEJAhCjICpYqkwNItzEIhG0qgnsvhfqBtHxEjAEzcTMI2Ht153zF0lWILdqcG46
            SBuG38gdY146O6wAS9DTALADDav4KTbAZAEYOT/026aSP1H+ay99G4QL0T0WMWlw
            u6lLuIALiw==
            =/vPY
            -----END PGP MESSAGE-----
          fp: 4C8C1857C468123F57E5C7E7A05D361B64156AA7
    unencrypted_suffix: _unencrypted
    version: 3.11.0
