---
apiVersion: v1
kind: Namespace
metadata:
  name: glauth
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: anza-labs
  namespace: glauth
spec:
  interval: 5m0s
  url: https://anza-labs.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: glauth
  namespace: glauth
spec:
  chart:
    spec:
      chart: glauth
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: anza-labs-github-io-charts
        namespace: placeholder
      version: "0.2.0"
  interval: 30m0s
  timeout: 10m0s
  releaseName: glauth
  test:
    enable: true
    ignoreFailures: false
  driftDetection:
    mode: enabled
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
      strategy: uninstall
      remediateLastFailure: true
  values: {}
