apiVersion: ENC[AES256_GCM,data:dy8=,iv:FlJ/IncKDSxOozqbXEN1xxMvouobg4UnyIT5BM7iqWg=,tag:6TfmPJHHKAcDus/JLqwK8Q==,type:str]
kind: ENC[AES256_GCM,data:ahNxZhOa,iv:7Mf3SfbUgizK5ShKMeNjjxAvyf6hVUZ8Kbs9GRGOtGw=,tag:3B+ogrHfucvedWEDTRw4IA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UOvWXlnW,iv:oXzx6GXPgdnSuJYV4M3B5khWJPKY7y+Ye77yavnbWqE=,tag:wK+FUe8P+FvGTyDUex666A==,type:str]
    namespace: ENC[AES256_GCM,data:hPrspt2t,iv:oZt/JSiQ97GH9vkVAFEqMzquYdLTXV0ZodIqcly5Azs=,tag:7KbS5JDGsqCQmTknXFyP/w==,type:str]
stringData:
    glauth.toml: ENC[AES256_GCM,data:7K3EYtJLexRwAeaIRewt+n7Kw3UR3FLFcDDINVVIz3ANItFPsByiUB/ibikFqaTegiPBgqQnZRiOAJwc9F02J8Y91tlct9AUdf/xONJxpI8H/EsP2RIFg5j7ID82aBFnswnmG1t+VxE21Mh13LYZ58ub3kz7nhLznZN7c5yuiUWaVVdzUiFsEgITbF2hwsB2C8E1G5suAn3gfKpdNu02VDZZGL7m7zxat39eyngusoZtIoxbLXzRYUVUureVTnqK4RKht8NAnjD/In98VUGs5B5QYGub/Ora+ElhoUTtoYDyAQmjhmMF0jqcCWiEknqNtCUy3jsr71/V5eEUYL3LO194bqQfWAW0o/rsX1VauZXJWKxAy7tq2hsFijH5saf0h8alitdN+FCXd4AsDSrPpQkwgVvNpIIv5kW3cRL1uK+NJeTzkLqdlj3qas0FKcGPeMnbC9wz4TsIPuBGAavECWrS5k3VS0ev/qRLHY1QATAIhWNYbGoKstUziz7lLmS6v7b1msECsWUlN4sKtI6XAFgiaEQ4oqYnwUb4Y4PGNKJ2PByN4lCMLLLr5+hjvwTnzzaOxjAnehFZRHrc64mSGexLkpffSe2Z66Ej7RWE1BhqTFhD5EnTTL+xFXx0UjC/r5XfzFJjgVRwE395DigjJa1wtmg9H1pYUjAo5UMZLGUyL/LoUlRrlbCCq+FWtJsKHyDZpy/hnmtnPlRfnXHdXHUPXPE/Aju3Xiz5Jrc8VhpR5KznW1DfyafYqR2MukEhi1w8hDRct2tVofRmnJ5cloMdAQsw4IEK3nn+Ea0mNLTfHrsv8Wl5FC2ffSUYdJdigXt9uO55tCM1i7IVW/fJG+owp/lGVBNUj/dmHPcltQIwne1WcMGDUZwwKi2fzY9a59xGdDU5dmKeyfPAwNRLc+MR1XPymRQM9inq7VyDEgwuOKsBxUJDrL8BiIef/UXNfAmtyfufeSDfbRyWt69XUe5alO1Ei4MgnKh+s6H5q06jo5zQeeZiKr9BP0um7KfonYaVV/7EdYUPVeWYJLMPna8hMlwH9F7wKoydNeXLBPmuVGfk2FTzG2xb9m4Sea+RtJe+0xn4hc78yhvNGo23eIEDex14HQXvTykz8ZBSDP2JgjsXhaGMF/stRbUwjNJU127igwMlrB5PRJA0PUfhi5MFry8dn+OCCGuoLruIibEYZJHuRRCuXpnBKLvmZAX5DMqlH36VeTc1a9UIwBJmHd9mshrSbep9jmE0fqtTh7S46HMSOMR6c9MY9I5elgD8omFWhEixQhBVjGCrJx3qNNktrMhX3vLhTVn9PFuAm+kHGuRuDREAx8PvvBHxlZ8KPBn86YUYi6TYekvBlQ8QnlNZGXxi5J5rjProf6yZDi2CngK88gGe1JiXU4z8tkX4Uok37tl/fQT377prV5AK6fupk5fulYgl,iv:Ek8CXfzz/BQmezWlIWu41cwrwCV2xYjbbj9Q11l2tVg=,tag:gUdIcdvP25h7CLcEjZYUZw==,type:str]
sops:
    lastmodified: "2026-03-02T21:45:08Z"
    mac: ENC[AES256_GCM,data:aVYuPnoq/EJx+mAVZUZCwG6cGzpb9/xuvXiNDx73W7WsdqLNPAOcZUSQS/8QcTMkcRIykZ+AG6uAiX4Wj76+uifoQ9hx7REyVwfeiCMeea5quZirGgfi5yCXV4+QrHbEh1VLUQqeT/Zh+cBZSFqy+1KwSUKdLH76/Y22Mn3zH4k=,iv:6PlRkz4HUoKdZIPk65VXdqZQR7CdgjPbb7qdnziO2dY=,tag:lsm5T0EestVhqUBxj+GDRA==,type:str]
    pgp:
        - created_at: "2026-03-02T21:45:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2aYMUUzTqIRAQ/8CblfLyz3I2TrYN2wXyt8w4jDmTUMJDez90bFXrSyBcy+
            7v8VPqClzUg2td0AwRQjfMQJZoNJKo6u9wt6Vm4zzwNv9wHwkLvq3wFV4e4hmgwH
            2qfpkYNevo6HrQyJeWklXD6upBA5JQBoDwchP2FZORFPEIgabwjvUVVBJu1v9Ebw
            7EJDLHo4+NKFGZfJNPpYF9QlXXAu1ZtHfEYzGd4NNdHHHxHAVhTGILGh59IxutHL
            St3ZFfPV4aX70TCktnsS0joK2nWFWSVHWU056ORaV8oOFUEquNmXo5lMi6Rtarrb
            kw2rfCO6ubqcBm3/JW30PLXgTWFzOBRO/DcRGDFsrGpKRaaZDOzojVxKQ0SFibUN
            hgDBmEWTfeOXqiJNrbb5S/+7lQj9RMPqWnAnHn6N4AqaeeP5txtmo1oXMl6xfel3
            Iim7dKgfo43OvipDt5YzXo0RftDvIJZRS9RnacxzUGTbVOvKmYrz0X1rPvSGNh0B
            NtrHy4fuECKPdb09CjcPsnwM4QisiqqmWeEGPxcYJ1PX1QFHxrREJWE91HAV6jsY
            TZWca6rtuxgM51erK0/lamBdQ+LTErAaQG/ck4I1yt4PNxi5XRk1vBFlDyH+N316
            TuECM6mgHVUVbc9TY9fistZecp8Xtr/WHZJaYguES/OPEfXJc5Nq6nM/cqy/LtTU
            ZgEJAhAgGk2jyapCrau7gTI1U9M/u0K1OSmTN2M47f7qkJYEhnYol/WnJZi7oxBB
            d8CctpUixaM4MAw9Z2zxnMw2xs9rMAFbbe4T412p+nuk1y26jJWVxnz0v/0aOMAk
            7sC/YDzpVg==
            =ih17
            -----END PGP MESSAGE-----
          fp: 4C8C1857C468123F57E5C7E7A05D361B64156AA7
    unencrypted_suffix: _unencrypted
    version: 3.11.0
