apiVersion: ENC[AES256_GCM,data:7es=,iv:LdMqRWPQMh13Y8M4mWnUrLQqm+5zIq80HKHpXva5BV4=,tag:3TxhahGP+9Q63Q/r5SFDsg==,type:str]
kind: ENC[AES256_GCM,data:/ewiGpRn,iv:pkeytva9T6VH1qeUo7VFZfldgMFXA7naUiUv6AiS8BI=,tag:YhjHiW4HrWJKHhTRVe+4Bw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0MjH/QLt,iv:dbdK9HxwFSEElSIVTZgmPT39m7cwKDzxKfhwPHkY8os=,tag:kYIlCjkoz0vmq1hNo01z3A==,type:str]
    namespace: ENC[AES256_GCM,data:qjPM68J7,iv:n+I+RC/V+t7LJWFHSJnqZ9e5Y2xpneSBuR9pv92W4L4=,tag:xRkAaLYJIFPShaNjJAb4Dg==,type:str]
stringData:
    glauth.toml: ENC[AES256_GCM,data:wEHlew+8Wg2Fb5798r38UCRXeiO54JPvw6kwKMIrWx5ccprSXHC+YrzwTdQgp4NcNTOySUpO1wdeNEx/d36aUiX84lczypbohGo4q3ViSrOPGKCTsv0rvK6G59/unkJ3xrImZe7suqHygxMssisxZwiwrfYcmSA4O19SlB7FzzaOcPDCTZ4t06QgRxvqOvhAcVtHCvG8/CEMOAcEOtLAc8Q5cEGGkDKs0cdus3+ae9FR9RO+73KJKPRJIKSmpxn3f5+zsYIyvykeVbePeHlQFOtFRKz7tHzWJARq+a0RHudABtVwEXOUsHj57jSoK15dw16CloNKw0cdoRllNe9EdgBQJBaGVJ122zwKCvgD2o1aezlC0rI0kjGJfHzuDcqMdg3ILOrv8VDgMvyyXJniIR8dbJqtzErWDXOKgLH6aVaKOEq1riZuAGHnjM67txvj2gQOKzFOg4nxokLTfl8Sg12ZR8o5s4KEmgwDFU2TwGr4mZFh8jU0ESEYHitZ36Ewh+d2BzPyeE53sFvcOdfgewx4OYjtMhbMXQKkFrHT8im8C8up2Fp6L/WyKztS798AAGqkKs5EVvciww8He2Rw5Ua5Ycz9i9m9CiRNR6quKl34E8N7P9GPGWJ+2SpUfqZVFtuncHiFe7hxcaoSGGHUC958to7xmikIQ8t5UZwCO+TGspvz/Yvafyb7yRwKizbs3HobxHobDPrixIj12OtObtDjvKfpwhdEvzcfk7clQXOp8VcnZA0BIDi8o6lCjxUxpq4jnRjILKm29wQr55AKFJUQtjMLDWLOLXg/01zRuu36gH4RD43GtSEDOfjTMMnbmTnl2G+0XoSrNMgW4MmrM+ULxiKsyLjCIN0D4E8AkxaSfpFqD5pz+LWTU/HSA6/JTeKyoFSx3gTMb6d6jn1gF7VliT5mghvjHHM7ciLo5gxOypqLFUTJOI5wIcSr/AKpwVFg7B5/OaMTlx0whKZ/iEr6CCBfZSPl8uZ07NHcGMKmMN1pW9yvnyn9QEzKOZo0V6/kTnz1pZGVmJToVcnhQDQ2PUh2yB/MRFGGXhBwO/EKZg4hiKZ4Gi4VQwtY8Ksxb970iaqTqhobd3r1+UEU31tpM3kNvD60Tr8wVkVctXDCs1xCQ/aeEiZsa7T0bwUbTwRMvGZqVJOzhSfFP8wBhmWExyq++OVzPhV6YTcBxtvcAdaET4jpbVt5YmAtUrO4wgpLgzpPX6NU1UoTMIsf+vahsk25cDDYS/kN2QeTk1pJrTCTPtIhMpZRJLDgPqf54kFIy5iAmKKWWGypiLCRbzMSLMDCmFen17ZUPahxUv2yNO420Pk1sO0Pt++qs3wJ5ydvfB1+aAOghvcYCntfjAHrgUUPCw+754LckKcxLloj+FWvu+A+Ala5vo5QidxZ/gM4kNwHZ5wCh88Qd5mm5R0BXV2obOej,iv:FyoJ0+NQ/RM3ZvoCnB3l9qrSExgbb4H+iMqoH1v5+tU=,tag:AlEKQyzc6GPnm6E3gsOIzg==,type:str]
sops:
    lastmodified: "2025-11-12T20:48:43Z"
    mac: ENC[AES256_GCM,data:ysbq2WHYfqN5/6cVXdGTA93XAJWmaBFPiaf9xo/vP7c/nL1Ygw4HzNj9Mp4iV1l0cADiCg5a9mqf9LJu9C+YasoPTPLtsYhJnf0UQkS7o1bHaLvJ7RkiPN6sIz///sGZnvqzGsoyjnZZbX88tel2CHF4+U61VZzCj0huYoS6RcY=,iv:9+Qf88zztYTKeV+9K0kKZWrYRf3yqGU+rcGG6qewEM8=,tag:S4A+ejILFVF6HUZdWyO9nw==,type:str]
    pgp:
        - created_at: "2025-11-12T20:48:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2aYMUUzTqIRARAAnm923iYlS3o69SMhQ4eDD3QKa7qcnZ6R7WJQh9ZeMJEA
            mTF4kj8zEY9nxn9k7D4G2c9nHIipqRr9FjOdKbIwWADtZSqItJDwxEnM4mfEHMZD
            o0gQ9rHT0OD8uOanLdXTGCxFOH0peHVg83SXEPmGA11tr9K0XCaCeNvaaMBqck7s
            oK+ZYYpWTN3gtj2huEUbXxv+aBMy7jd+rZa6Pl7CXXPhnU6Tb6x7FKkrc+sTuX23
            +DxQv3+qENBmSREcfBUgrZHVwxjQ3JK51AM6sceZkoRZFpbrf0BVeWPIbSt9RNlP
            9z9w4sCAiLHOUFGVLUMZ0nHVH4EqeBz4w0JXxYOOo+cyrtdp0nL2n0s1nsXsznkp
            zaPWDiuIWRNmsIqRp8q7zBOSWtVa11hIMcU0eeBJHRwRUbmYpzxHeAAGa7w8GNyM
            eFCE6VnFQ7LSqmUa0ugs8RXqCCM18KBGKdJQ7wmptPsBm3lEAlESb7YtrRj77AAs
            uaAvdc0KxMO2eVDxV4dbpWDjfQZieJ/ZRLSH4i787K3qEqslneuOYkcFq1LL9XLR
            b8RkWv4zxISZ4jWtc04i1rx47mDaXSB2r8yv1dwBlcO8nj5TOeKx+aZwtpixB4vs
            HC9tMahNLrdxkp2mTa7FIJgmIvGzLNdrs/PAegAxIOVY8pTkqG1CjrONemSWosHU
            aAEJAhDxy/1Qffl3wBcj34AEtVQcM/PpcEBZskyFQ/TlcY7FUK+/ol9UL111i9nD
            k9E2HDWgN8jN8cKJ5KK5ic7lRJ7YZLQ8dVYUVYR46P7tCQWWhCoA6e3Kz30do9mg
            45f/XWefYr/v
            =Jl6e
            -----END PGP MESSAGE-----
          fp: 4C8C1857C468123F57E5C7E7A05D361B64156AA7
    unencrypted_suffix: _unencrypted
    version: 3.11.0
