apiVersion: ENC[AES256_GCM,data:69Y=,iv:jzwRCRZndDsj0E3Y0pe1tUx3wvqEXmRcDME+i0jDQzc=,tag:/rub3Ga3XEY19Qj/0tmFNw==,type:str]
kind: ENC[AES256_GCM,data:putk84F7,iv:N//cgfYKBNPMoOc3cFit/T9i6ZKFVYIjeBhYB3Wiwes=,tag:r4J5ek1XV0UF383lyr2T/A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GtXc6pjw,iv:jmREelmXl/+2C4K7D33H0BbMUbyXqAL1vAbMZkXwrEY=,tag:MgrX44u/6LOuIwtWJyZFzQ==,type:str]
    namespace: ENC[AES256_GCM,data:PY1rCxV+,iv:JyVftT0pBP2cBe6ZkYjPrFBISLEm3pjeJtQX1cZLAcI=,tag:7iySkbbxE/oQ2GROoWV+fg==,type:str]
stringData:
    glauth.toml: ENC[AES256_GCM,data:g6ulrZO9Xln8xlb0KXXDPqj4S2DEcOlOFbK/F1MGVoONNFUhsZqCjBJHBSTTgiOXJrafV0nt4Du9JIHXOtKNo5BHQcmfiAfn/4TgoIzB+32A9WrQDloM4wH8reUDsmj2kkl/3vkQLXXLB6XoHVTvATk1pGw89mbxd9v5Ztk0hz/jdVcPvwvU/SX7STFb3aipHL4HtUiSS+93rUdK5Kzn1EPPA9QrmVEHTM17/96fBtr0RL7XzIhClAomHFi/tlGGRlsOb706yZ/HsjoeqXcwm3mHMj/lFye8pgBlC5wF9a+9GJU0M1SqC5aLZLDARnLyLGK2oRfr3JHgqsu9IVg4YUX65zm0I0rGYSMl2I/Ulb1qOo8MAEvjL9wLuVrT4liF6YEu4eJQMfRDfHQJhz1cHiNiHy86FWFM70OZjZP/uP1XftJlSCuLCFos/bbFW1uC6/K5644Lcf4mrlM40T7rcXpInCIxhiSXI1SUvRcSInwPIR4Hou1gRc+dMGJ/Ffwu/huA/Up8a2vNJ+7RCDgRIXgCRBlfKtW2yOnRDgaQVMAIS8HZCkulrVPvVJ1R4Jn3hB1Q99AcNV8KXdZy7hlsG9QcYc3bKxY9QIvhg+0OzCDJe9tx20XBVpSUMqFHhgmC2dG/S4X9AxHRYPRgqCi/L0ncYWqvBvwgkOSBESwsRg6qO6WvmAcpTIZWzftgFGNNUjYQKVJlAwOV5AtGmEd+oI/Yi/uqC2Q7I0mDvv7K4I/Iqd8UOJI8pnpZZ2fWv3Wt1k6BVDAtlsBm4slxWuJmrxFPM4cbVbD7KawMdJcgkaoPRZj+YeQf/k4AZ7L75W7PjggdDBYNtfQVk4q8EEfH1kqt8QhYM1l9OG4vhKngcdT2e39SZanSwz7QokFCx8ZjHEuL9Xg5Uyke9D0QDR7zO1QL3sQIzsMfL+muwmZdvAXMw6ExZ1qh6hWj/Zck9K6a3QbAQyW4MRagSZJ1QRFKbe0FmHbH4bnwaTQB9GqbZaFbrt0EoksGI2vMVPbutDuaDNjrAjphQzN7KsSQ/IEMzyjgV7HnjfytrFPfxRBpsKSU6duQGLrNKZc8VZNjBzDt4n+RhFpQ8U8n5HoGZxhnYo17SA3Rdtsr1kSlkB18t2u4JLtcUGaxcJ3OJZJkB9ADxl9ESaLTZ7nY/qQ5O5MySE2JXrJxUDiqS2CvUfpko1Gn4k1odoZvjIIgMXJNJOj0TsXsysKqEd85mU50gpkgXCpAXt0p/LpZUzd07U+1B3QBZqEQ4XFLEmL93KDydk0ugybjZEa9aaFKomQ0Ou6Mr8qKAISzJ0W4RvxFDkAFdQpRcuRF01PhOniyPp+e0Gth6dSEvNTmwUuuQANwsx0zMlDrJDSXSm8dNBxesfGRG7/+Zit8Y28mdtD+9AXxdYhoI6jKRjHI16jGOBv4EPeFLaDEeEE3JbOj,iv:GVqnlVFSJNbHegw1wGdSRvstYS9z4zWi+/WyY+oeh2I=,tag:o78AXJgfeXgpUNMwc7PLTA==,type:str]
sops:
    lastmodified: "2026-01-06T10:45:27Z"
    mac: ENC[AES256_GCM,data:vZA2iNv8et+TvurTpiciTBLNLNTtfl38VqbtSbEV5pA7dq1Xf95mTfFfQCnfbO/k1xstlmVVCLC6qNUCTlfh3Ued1MiuPnU5eW72sMxyX/EIKBidklFVfbO8nXrh1AA2kAgS5jTioaSz6dstHjzhygmYh0dXBRmjZ3Wt8NJiRm8=,iv:4TYTcveE4cyFWl1E8K4PqdzQ5k0M6Y8U1jjUMgVmob0=,tag:gf5QljJbBR5Bn4mlPL04Tg==,type:str]
    pgp:
        - created_at: "2026-01-06T10:45:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2aYMUUzTqIRARAApYAVlPUCGusfp/WqoBUBeHnjcvYEqDzRXVHjNsrSJp9m
            bd20xLXILInYQDAQDcAYIdF5IdA3uzOxpRQuLv4uGqpo0iAr+HqAIctosSXEV4WQ
            fj3r4Fe4eV+XuuG1UIRvRGi/e0U3/pynn4oPhtq3qaOkhMrjadFmJtYy/lohUdm5
            p9GRkrFfQdrbdLK5rqh2jakGgzELsTLxJgxZbSLFRUiW3NczTS4tbWm8uWu3mVUT
            WclDQgv6BgcPgcXQT5CCyo0fZTzGM6kuoOIQxnQG7zVrymN5lAMxy520E6w1iRO6
            nXVgyVI9HoYLinoZgq6RU/ya/WTs3ktnDObGX+w36J0NKEwHeJLRRE5RBBpP0SsT
            S9/lw8OxDLclqT9yHfS7+eBrX4AstwaQ3RsMIAqkUQeNClDJnLjlRleY6T2ncr3t
            rXLkeuIsb4/AfctDi2oLfRMdiU9fQgE0BUhKTES0CR67M8teEy6wvYcX40GynUum
            yTHTOrjQQhWFW+lyu5A4Dviafhko3wKE1oqouKuClS4Qj/kgy2DOXg7kRwg3D01r
            4vnLs3cZMNZtSLrnHEvoke6ZmKV67mi1W5u1QdyLCXVbGjJNLWKUrrNyFsljXFHO
            fYNYPMxnCqOKg/YOHYfglTiKLsMddgLgECA9ZpmYRXM1QXdW3uqZNjsBzqe0nuPU
            aAEJAhBf8+Wy4poCKz3xC0TMK7M8HUwysqGR706sMxK0RFA0YiH6ttab3jePxYDW
            JF/cbtJwiKOKMQ5LZcRqErkrkTSMmA3x1ntlCzdU73jY75L3S56nWLWaGaU2+5IT
            wAglgToIJiLW
            =M1ee
            -----END PGP MESSAGE-----
          fp: 4C8C1857C468123F57E5C7E7A05D361B64156AA7
    unencrypted_suffix: _unencrypted
    version: 3.11.0
