---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth-credentials
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: client_id
    remoteRef:
      key: "49eb5899-a5df-4ab5-88fd-b30900b212cf"
  - secretKey: client_secret
    remoteRef:
      key: "31f2fb0e-bb3f-419d-8660-b30900b2288e"
