---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth-credentials
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: client_id
    remoteRef:
      key: "2762ea5a-21b6-4f47-a601-b30900c7e748"
  - secretKey: client_secret
    remoteRef:
      key: "70d4af7b-6127-43dd-adb8-b30900c8292c"
