---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-ini
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: "grafana.ini"
    remoteRef:
      key: "b43998dd-19a4-4e6c-9291-b30900c036a6"
