name: melody-auth

on:
  push:
    branches:
      - "main"
    paths:
      - "configs/melody-auth/**"
      - ".github/workflows/melody-auth.yaml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}

env:
  # renovate: datasource=github-releases depName=ValueMelody/melody-auth
  MELODY_AUTH_VERSION: "v1.3.7"

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/checkout@v6
        with:
          repository: ValueMelody/melody-auth
          ref: ${{ env.MELODY_AUTH_VERSION }}
          path: melody-auth
      - uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: melody-auth/server/package-lock.json
      - run: npm ci
        working-directory: melody-auth/server
      - run: npm run build
        working-directory: melody-auth/server
      - run: cp ${{ github.workspace }}/configs/melody-auth/server.wrangler.toml melody-auth/server/deploy.wrangler.toml
      - uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_KEY }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      - run: |
          cd melody-auth/server

  # admin-panel:
  #   needs: [server]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v6
  #     - uses: actions/checkout@v6
  #       with:
  #         repository: ValueMelody/melody-auth
  #         ref: ${{ env.MELODY_AUTH_VERSION }}
  #         path: melody-auth
  #     - uses: actions/setup-node@v6
  #       with:
  #         node-version: "22"
  #         cache: npm
  #         cache-dependency-path: melody-auth/admin-panel/package-lock.json
  #     - run: cp ${{ github.workspace }}/configs/melody-auth/admin-panel.env melody-auth/admin-panel/.env.production
  #     - run: npm ci
  #       working-directory: melody-auth/admin-panel
  #     - run: npm run cf:build
  #       working-directory: melody-auth/admin-panel
  #     - uses: cloudflare/wrangler-action@v3.14.1
  #       with:
  #         apiToken: ${{ secrets.CLOUDFLARE_API_KEY }}
  #         accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  #         workingDirectory: melody-auth/admin-panel
  #         command: deploy
