name: tests

on:
  pull_request:
    branches: [ '*' ]
  push:
    branches:
      - "main"

jobs:
  render-kustomize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: imranismail/setup-kustomize@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: |
          python3 -m venv venv
          . ./venv/bin/activate
          pip install -r ./requirements.txt
      - run: |
          . ./venv/bin/activate
          python3 ./hack/patches.py \
            './flux/manifests/k3sup/flux-apps.yaml' \
            ./tmp
      - run: |
          ./hack/test.sh
